<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/ch2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part1/ch2/ch2_pandas.ipynb)

# 판다스

## Section1. 데이터프레임과 시리즈

In [567]:
# 판다스 라이브러리 불러오기
import pandas as pd

In [568]:
import pandas as pd

In [569]:
menu = pd.Series(['비빔밥','김치찌개', '된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [570]:
# 시리즈 만들기 (문자열)
menu = pd.Series(['비빔밥', '김치찌개', '된장찌개','청국장'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
3     청국장
dtype: object

In [571]:
# 시리즈 만들기(정수형)
price = pd.Series([10000, 9000, 8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [572]:
total = pd.Series([10000, 20000, 30000, 50000])
total

0    10000
1    20000
2    30000
3    50000
dtype: int64

In [573]:
pd.DataFrame({
    '메뉴' : menu,
    '가격' : total
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개  20000
2  된장찌개  30000
3   청국장  50000

In [574]:
# 데이터 프레임 만들기 pd.DataFrame({"컬럼명":데이터})
pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

     메뉴       가격
0   비빔밥  10000.0
1  김치찌개   9000.0
2  된장찌개   8000.0
3   청국장      NaN

In [575]:
# 데이터 프레임 만들기 pd.DataFrame({"컬럼명":데이터})
df = pd.DataFrame({
    "메뉴":['비빔밥', '김치찌개', '된장찌개'],
    "가격":[10000, 9000, 8000],
    "원산지":['국내산', '국내산', '국내산']
})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [576]:
df = pd.DataFrame({
    'MENU':['비빔밥','계란후라이','계란말이','스크램블'],
    'PRICE':[10000, 4000, 50000, 120000],
    '원산지':['국내산','외국산','칠레산','호주산']
})
df

    MENU   PRICE  원산지
0    비빔밥   10000  국내산
1  계란후라이    4000  외국산
2   계란말이   50000  칠레산
3   스크램블  120000  호주산

In [577]:
## 시리즈 선택
df['MENU']
df['PRICE']

0     10000
1      4000
2     50000
3    120000
Name: PRICE, dtype: int64

In [578]:
# 시리즈 선택 (가격)
df['메뉴']

KeyError: '메뉴'

In [ ]:
# 데이터프레임 선택 (가격)
df[['메뉴']]

In [ ]:
df[['MENU','PRICE']]

In [ ]:
df[['메뉴', '가격']]

In [ ]:
# 데이터프레임 선택 (가격)
cols = ['메뉴', '가격']
df[cols]

In [ ]:
## 하나로 합치기
cols = ['MENU','PRICE']
df[cols]

In [ ]:
## 데이터 프레임 type 확인
print("df       : ", type(df))
print("df['price']       : ", type(df['PRICE']))
print("df[['price']]       : ", type(df[['PRICE']]))

In [ ]:
# 데이터 프레임 type 확인
print("df          : ", type(df))
print("df['가격']   : ", type(df['가격']))
print("df[['가격']] : ", type(df[['가격']]))

In [579]:
## 데이터 준비
df = pd.DataFrame({
    "MENU" : ['아메리카노','카페라떼','카푸치노','카페모카','밀크티','녹차','말차'],
    "PRICE" : [4000, 4500, 4400, 4700, 5200, 2000, 4000],
    "KCAL" : [10, 110, 270, 300, 320, 20, 30]
})
df

    MENU  PRICE  KCAL
0  아메리카노   4000    10
1   카페라떼   4500   110
2   카푸치노   4400   270
3   카페모카   4700   300
4    밀크티   5200   320
5     녹차   2000    20
6     말차   4000    30

In [580]:
## .csv 파일로 만들어서 저장 및 확인
df.to_csv('tea.csv')  ## to_csv() 함수 사용 '이름'
tea_df = pd.read_csv('tea.csv') ## df로 저장 pd.read_csv(만든.csv)
tea_df.head()

   Unnamed: 0   MENU  PRICE  KCAL
0           0  아메리카노   4000    10
1           1   카페라떼   4500   110
2           2   카푸치노   4400   270
3           3   카페모카   4700   300
4           4    밀크티   5200   320

## Section2. 데이터 저장 및 불러오기

In [581]:
# 데이터 준비
df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리":[10, 110, 250, 110, 20, 210, 0],
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [582]:
df.to_csv('temp.csv')

In [583]:
temp_df = pd.read_csv('temp.csv')
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [584]:
# 데이터 불러오기
df.to_csv('cafe.csv', index=False)
df = pd.read_csv('cafe.csv')
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

## Section3. 탐색적 데이터 분석(EDA)

In [585]:
# 데이터 샘플 확인: 앞에서 부터 n개 (기본 5개)
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [586]:
df.head(2)
df.tail(5)

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [587]:
# 데이터 샘플 확인: 뒤에서 부터 n개 (기본 5개)
df.tail(3)

      메뉴    가격  칼로리
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [588]:
df.sample(3)

      메뉴    가격  칼로리
4  에스프레소  4000   20
3   카푸치노  5000  110
0  아메리카노  4500   10

In [589]:
df.sample(5)

      메뉴    가격  칼로리
2   카페모카  5500  250
1   카페라떼  5000  110
0  아메리카노  4500   10
6     녹차  5300    0
5    밀크티  5900  210

In [590]:
df.shape ## 데이터 프레임 크기 (행, 컬럼) 개수

(7, 3)

In [591]:
df.info() ## index Column_name Non_Null type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [592]:
# 데이터 프레임 크기 (행, 컬럼)
df.shape

(7, 3)

In [593]:
# 컬럼 형태(type)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [594]:
# 상관관계
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [595]:
### 상관관계 출력
df.corr(numeric_only=True)
df.corr(numeric_only=True) ## df.corr(numeric_only=True) 손에 안 익는다ㅏ

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [596]:
# 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car":['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    "size":['S','M','S','S','M','M','L','S','S', 'M','S']
})
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [597]:
## 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car" : ['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    "size" : ['S', 'M', 'S', 'S','M','M','L','S','S','M','S']
}) ## 두 항목의 길이가 같아야 함

In [598]:
df_car.nunique() ## unique X nunique O (중복되지 않는 데이터 수)

car     2
size    3
dtype: int64

In [599]:
# 항목 종류 수
df_car.nunique()

car     2
size    3
dtype: int64

In [600]:
# 항목 종류
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [601]:
## 항목 종류 (중복되지 않는 데이터)
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [602]:
print(df_car['car'].value_counts()) ## 항목 별 개수 계산
print(df_car['size'].value_counts()) ## 데이터프레임['항목'].value_counts() count에 s붙이기

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [603]:
# 항목별 개수
print(df_car['car'].value_counts())
print(df_car['size'].value_counts())
df.describe() ### col 개수, 평균, std, 최소 최대, 4분위수

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [604]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [605]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [606]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [607]:
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

## Section4. 자료형 변환

In [608]:
# 데이터 준비
data = {
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리":['10', '110', '250', '110', '20', '210', '0'],
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [609]:
### 데이터 생성
data = {
    "MENU":['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    "PRICE":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "KCAL":['10','110','250','110','20','210','0']
}
df = pd.DataFrame(data)
df.info() ## Non-Null Count 개수가 3개 모두 동일한 지 확인 + 인덱스 번호랑 column이름 정확한지 확인, 자료형 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      float64
 2   KCAL    7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [610]:
## 자료형 변환하기 / astype / object -> int (형변환 확인)
df['PRICE'] = df['PRICE'].astype('int')
df.info()
## df['PRICE'] = df['PRICE'].astype('int')  ## 데이터['항목'].astype('자료형')
df['KCAL'] = df['KCAL'].astype('float')
df.info() ## KCAL 항목을 object 에서 float(실수형)으로 변환

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      int64
 2   KCAL    7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      int64
 2   KCAL    7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [611]:
# 자료형 변환 / astype /  object -> int
df['가격'] = df['가격'].astype('int')
df.info()

KeyError: '가격'

In [ ]:
df['칼로리'] = df['칼로리'].astype('float')
df.info()

## Section5. 새로운 컬럼 추가

In [ ]:
df = pd.read_csv('cafe.csv')
df.head(2)

In [ ]:
## 컬럼 추가
df = pd.read_csv('cafe.csv')
df.head() ## .head() 함수의 경우 데이터를 5행 출력해서 보여줌

In [ ]:
df['new'] = 0
df.head() ## 행 항목이 아닌 열 항목(세로축)으로 값이 0인 new 컬럼이 추가됨

In [ ]:
### 할인가 항목 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount) ## 1-0.2 = 0.8 (20% 할인가를 의미)
df.head()

In [ ]:
# 새로운 컬럼 추가 (값은 0)
df['new'] = 0
df.head(2)

In [ ]:
# 할인가 컬럼 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount)
df.head(2)

## Section6. 데이터 삭제 (컬럼, 행)

In [ ]:
df = pd.read_csv('cafe.csv')
df.head(3)

In [ ]:
df = pd.read_csv('cafe.csv')
df.head()

## 행 삭제
df.drop(1, axis=0, inplace=True) ## 인덱스 1번에 해당하는 행 삭제(0부터 시작)
df.head() ## .drop('번호', axis=0, inplace=True)

### 행 삭제

In [ ]:
# 행 삭제
df.drop(1, axis=0, inplace=True)
df.head(3)

In [ ]:
## 컬럼 삭제 axis=0일 경우, 행(가로) 삭제 axis=1일 경우, 열(세로)삭제
df = df.drop('칼로리', axis=1)
df.head() ## .drop('열 이름', axis=1) 열 삭제

### 컬럼 삭제

In [ ]:
# 데이터 삭제
# axis=0:행방향, axis=1:열방향(컬럼)
df = df.drop('칼로리', axis=1)
df.head(3)

## Section7. 인덱싱/슬라이싱(loc)
- 인덱스 명
- 인덱스 명(범위), 컬럼 명(범위)

In [ ]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head(2)

In [ ]:
## 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head()

df.loc[0] ## 행 전체 가져오기  오 행, 열 헷갈리네

In [ ]:
df.loc[1, '가격'] ## 카페라떼 loc[1]의 '가격' 항목 가져오기

In [ ]:
# 인덱싱 (행 전체)
# 아메리카노
df.loc[0]

In [ ]:
# 카페라떼 가격
df.loc[1, "가격"]

In [ ]:
## 어렵네 이번거
df.loc[:, '가격'] ## 모든 행의 가격 항목만 전체 출력

In [ ]:
# 슬라이싱 (컬럼 전체)
# 가격
df.loc[:, "가격"]

In [ ]:
# 슬라이싱
df.loc[2, '메뉴':'칼로리']

In [ ]:
df.loc[2, '메뉴':'칼로리'] ## .loc[2] 카페모카의 '메뉴'부터 '칼로리'까지 (중간에 가격 포함)

In [ ]:
# 슬라이싱
# 카페모카 메뉴와 칼로리
df.loc[2, ['메뉴', '칼로리']]

In [ ]:
# 슬라이싱
df.loc[1:3, '메뉴':'가격']

In [ ]:
df.loc[1:3, '메뉴':'가격'] ## 인덱스 1부터 3까지의 '메뉴' 부터 '가격' 항목까지 가져오기

## Section8. 인덱싱/슬라이싱(iloc)
- 인덱스 번호
- 인덱스 번호(범위), 컬럼 번호(범위)

In [ ]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
#df.drop(0, axis=0, inplace=True) # 첫번째 행 삭제
df.head(2)

In [ ]:
## 기초만 하다가 시험보게 되는거 아녀
df = pd.read_csv('cafe.csv')
df.drop(0, axis=0, inplace=True) ## 0번으로 들어가는 행 삭제
df.head()

In [ ]:
# 인덱싱 (행 전체)
# 카페라떼
df.iloc[0]

In [ ]:
## 보여줘 카페라떼
df.iloc[0]  ## loc iloc 차이를 알아두기 (loc: 이름기반 / iloc: 순서기반)

In [ ]:
df.iloc[:, 1] ## 모든 행의 가격(,iloc[1])을 출력

In [ ]:
# 슬라이싱 (컬럼 전체)
# 가격
df.iloc[:, 1]

In [ ]:
# 슬라이싱
# 카페모카 메뉴와 가격
df.iloc[2, 0:2]

In [612]:
df.iloc[2, 0:2] ## iloc[2] = 카푸치노 iloc[, 0:2] = 메뉴 부터 가격 까지

MENU     카페모카
PRICE    5500
Name: 2, dtype: object

In [613]:
# 슬라이싱 (카페라떼와 카페모카의 전체 데이터)
df.iloc[1:3]

   MENU  PRICE   KCAL
1  카페라떼   5000  110.0
2  카페모카   5500  250.0

In [614]:
df.iloc[1:3] ## 모든 항목을 출력하는데, 인덱스 1부터 3까지 해당하는 행만 출력하는거

   MENU  PRICE   KCAL
1  카페라떼   5000  110.0
2  카페모카   5500  250.0

In [615]:
df.loc[2:3, '메뉴':'칼로리'] ## loc[2:3]은 카페모카-카푸치노에 해당하는거 / '메뉴', '칼로리' 항목 값 출력

KeyError: '메뉴'

In [ ]:
df.loc[2:3,'메뉴':'칼로리']

## Section9. 데이터 추가/변경

In [ ]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head(2)

In [ ]:
## 데이터 다시 불러오기. 다.시. 불러오기.
df = pd.read_csv('cafe.csv')
df.head()

## 새로운 거 나오네
import numpy as np
df['원산지'] = np.nan ## 원산지 컬럼 만들고 일단 결측값으로 추가함 (np.nan = NaN) numpy가 제공하는 NaN 값임
df.head()

In [ ]:
# 결측값으로 추가, 원두 컬럼을 만들고 결측값(NaN)으로 대입
import numpy as np
df['원산지'] = np.nan
df.head(4)

In [616]:
# 아메리카노의 원두는 '콜롬비아' 데이터 추가
df.loc[0, "원산지"] = '콜롬비아'
df.loc[2:3, "원산지"] = '과테말라'
df.head(4)

    MENU  PRICE   KCAL   원산지
0  아메리카노   4500   10.0  콜롬비아
1   카페라떼   5000  110.0   NaN
2   카페모카   5500  250.0  과테말라
3   카푸치노   5000  110.0  과테말라

In [617]:
### 원산지 항목 추가 '콜롬비아'와 '과테말라' 산 원두를 추가할 것임
df.loc[0, "원산지"] = '콜롬비아' ## 우선 첫번째 행 인덱스가 0이니까 0번째 값으로 '콜롬비아' 추가함
df.loc[2:3, '원산지'] = '과테말라' ## 인덱스 개념 숙지를 위해 하나 건너뛰고 2번부터 3까지 '과테말라' 추가함
df.head()

    MENU  PRICE   KCAL   원산지
0  아메리카노   4500   10.0  콜롬비아
1   카페라떼   5000  110.0   NaN
2   카페모카   5500  250.0  과테말라
3   카푸치노   5000  110.0  과테말라
4  에스프레소   4000   20.0   NaN

In [618]:
# 리스트 형태로 데이터(행) 추가
df.loc['시즌'] = ['크리스마스라떼', 6000, 300, '한국']
df.tail(3)

       MENU  PRICE   KCAL  원산지
5       밀크티   5900  210.0  NaN
6        녹차   5300    0.0  NaN
시즌  크리스마스라떼   6000  300.0   한국

In [619]:
## 시즌메뉴를 추가할 것임, 인덱스 넘버는 특별하게 '시즌'으로 하고, 메뉴명은 '크리스마스라떼'로 추가함
df.loc['시즌'] = ['크리스마스라떼', 6000, 300, '한국'] ## 모든 항목을 추가할 것임. 이름 부터 가격, 칼로리, 아까 추가한 원산지
df.tail()

       MENU  PRICE   KCAL   원산지
3      카푸치노   5000  110.0  과테말라
4     에스프레소   4000   20.0   NaN
5       밀크티   5900  210.0   NaN
6        녹차   5300    0.0   NaN
시즌  크리스마스라떼   6000  300.0    한국

In [620]:
# 딕셔너리 형태로 데이터(행) 추가
df.loc[7] = {'메뉴':'딴짓커피', '가격':2000, '칼로리':20}
df.tail(3)

       MENU   PRICE   KCAL  원산지
6        녹차  5300.0    0.0  NaN
시즌  크리스마스라떼  6000.0  300.0   한국
7       NaN     NaN    NaN  NaN

In [621]:
## 직접적으로 항목명을 지정해서 추가하는 방식을 알아볼것임
df.loc[7] = {'메뉴':'딴짓커피', '가격':2000, '칼로리':20} ## 7째 행으로 key-value 값을 모두 기재하여 추가함
df.tail()  ## 빅분기 준비하다가 거북목 생기겠슴

       MENU   PRICE   KCAL  원산지
4     에스프레소  4000.0   20.0  NaN
5       밀크티  5900.0  210.0  NaN
6        녹차  5300.0    0.0  NaN
시즌  크리스마스라떼  6000.0  300.0   한국
7       NaN     NaN    NaN  NaN

In [622]:
## 시즌메뉴 끝나서 행 날릴거임
df.drop('시즌', axis=0, inplace=True) ## 시즌 '행' axis=0 을 날릴 것임
df.to_csv('cafe2.csv',index=False) ## 다음에도 사용할 거라 새 파일로 저장하는 단계임. 물론, 인덱스 번호는 제외하고

In [623]:
df.drop("시즌", axis=0, inplace=True)
df.to_csv('cafe2.csv', index=False)

KeyError: "['시즌'] not found in axis"

## Section10. 정렬

In [ ]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

In [ ]:
## 정렬하기
df = pd.read_csv('cafe2.csv') ## 아까 새로 저장한 cafe2.csv 불러올 것임
df.head()
df.tail()

In [ ]:
## 인덱스 기준 내림차순으로 정렬하자 ascending=False "내링차순 : 숫자가 내려가는 순서" - 기본값은 ascending=True
df.sort_index(ascending=False)

In [ ]:
# 인덱스 기준 (기본값 ascending=True)
df.sort_index(ascending=False)

In [ ]:
# 값 기준 (기본값 ascending=True)
# 메뉴 기준 정렬
df.sort_values('메뉴',ascending=False)

In [ ]:
## 인데스 번호 말고 값 기준으로 정렬해보기
## 1. 메뉴 이름 기준으로 내림차순 정렬 (ㅎ->ㄱ 순으로 감)
df.sort_values('메뉴', ascending=False)

In [ ]:
## 두 가지 조건 적용
## 가격과 메뉴를 기준으로 정렬 할 것임
df.sort_values(['가격','메뉴'], ascending=[False,True], inplace=True)  ## inplace=True 는 해당 조건으로 직접 변경을 의미함. 따로 저장할 필요가 없음
df  ## '가격'은 내림차, '메뉴'는 오름차...가 아닌데? 가격 내림차순

In [ ]:
# 가격과 메뉴 기준 정렬
df.sort_values(['가격', '메뉴'],ascending=[False, True], inplace=True)
df

In [ ]:
## 인덱스를 새로 생성함 drop=True (정렬 전 인덱스 버리기) .reset_index(drop=True) ## 인덱스 재정렬 하면서 기존 인덱스 버린다고 drop=True
df.reset_index(drop=True)

In [ ]:
# 인덱스 새로 만들기 drop=True
df.reset_index(drop=True)

## Section11. 필터링

In [ ]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

In [ ]:
df = pd.read_csv('cafe2.csv')
df.head()  ## 해 뜰 시간이 다 됐네..

In [ ]:
## 조건에 해당하는지 boolean 값으로 확인
df['칼로리'] < 50

In [ ]:
df['칼로리'] < 50

In [ ]:
## 1개 조건으로 필터링
cond = df['칼로리'] < 50
df[cond]  ## 필터링 조건은 '' 으로 묶는거 아님 항목이 아니니까. 대충 칼로리가 50 미만인 값들만 필터링해서 보여줌

In [624]:
# 1개 조건
cond = df['칼로리'] < 50
df[cond]

KeyError: '칼로리'

In [ ]:
# 1개 조건
df[df['칼로리'] < 50]

In [ ]:
## 아예 직접적인 명시
df[df['칼로리'] < 50]

In [625]:
cond = df['칼로리'] < 50 ## 칼로리가 50 미만인 조건을 줌
df[~cond]  ## 근데 나는 50 이상인 데이터가 필요해 ~ (NOT) 붙여주기

KeyError: '칼로리'

In [ ]:
cond = df['칼로리'] < 50
df[~cond]

In [626]:
# 2개 이상 일때 (AND)
cond1 = df['가격'] >= 5000
cond2 = df['칼로리'] > 100
df[cond1 & cond2]   ## 조건 1을 cond1로 걸음 / 조건 2를 cond2로 걸음 / 두 조건을 df[cond1 & cond2]로 묶어버림
## OR 도 같은 맥락에서 | 로 묶어버림

KeyError: '가격'

In [ ]:
# 2개 이상 일때 (OR)
df[cond1 | cond2]

In [ ]:
# 문자열 1개 조건
# 원두 == 콜롬비아
cond = (df['원산지'] == "과테말라")
df[cond]

In [ ]:
## 행 조건을 걸어버림
cond = (df['원산지'] == '과테말라')
df[cond] ## df에 끼워넣음

In [ ]:
# 문자열과 숫자 조건 (AND)
cond1 = df['원산지'] == "과테말라"
cond2 = df['가격'] <= 5000
df[cond1 & cond2]

In [627]:
df['메뉴'].isin(['녹차'])

KeyError: '메뉴'

In [ ]:
## 조건에 맞는지 확인(boolean 값 확인)
df['메뉴'].isin(['녹차']) ## '메뉴' 이름에 '녹차' 값이 isin (존재하는지) 확인

In [ ]:
cond = df['메뉴'].isin(['녹차'])
df[cond]

In [ ]:
box = ['녹차','카푸치노','카페라떼']
cond = df['메뉴'].isin(box)  ## isin() 은 함수니까 ()임. 안에는 항목
df[cond]

In [628]:
box = ['녹차', '카푸치노', '카페라떼']
cond = df['메뉴'].isin(box)
df[cond]

KeyError: '메뉴'

## Section12. 결측치 처리

In [ ]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

In [629]:
## 오 이거 중요함 1번 문제
df = pd.read_csv('cafe2.csv')
df.head()

    MENU   PRICE   KCAL   원산지
0  아메리카노  4500.0   10.0  콜롬비아
1   카페라떼  5000.0  110.0   NaN
2   카페모카  5500.0  250.0  과테말라
3   카푸치노  5000.0  110.0  과테말라
4  에스프레소  4000.0   20.0   NaN

In [630]:
## 결측치가 있는지 확인
df.isnull()

    MENU  PRICE   KCAL    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7   True   True   True   True

In [631]:
df.isnull()

    MENU  PRICE   KCAL    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7   True   True   True   True

In [632]:
# 컬럼별 결측치 확인
df.isnull().sum()

MENU     1
PRICE    1
KCAL     1
원산지      5
dtype: int64

In [633]:
## 컬럼별 결측치 확인하기
df.isnull().sum()  ## df.isnull() - 모든 컬럼, 행에 대하여 결측치 확인 / df.isnull().sum() - 합산해서 한 눈에 보기

MENU     1
PRICE    1
KCAL     1
원산지      5
dtype: int64

In [634]:
# 컬럼별 결측치 확인
df.isna().sum()

MENU     1
PRICE    1
KCAL     1
원산지      5
dtype: int64

In [635]:
df.isna().sum() ## 원산지 어디감

MENU     1
PRICE    1
KCAL     1
원산지      5
dtype: int64

In [636]:
df.isna().sum() ## NaN 값 확인 isna() <-> isnull()

MENU     1
PRICE    1
KCAL     1
원산지      5
dtype: int64

In [637]:
## 원산지 결측값을 '코스타리카'로 채우기
df['원산지'].fillna('코스타리카', inplace=True) ## 아까 drop하고 얘 결측치 .fillna() 에 inplace=True 확인할 것
df

/tmp/ipykernel_13619/3518602803.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카', inplace=True) ## 아까 drop하고 얘 결측치 .fillna() 에 inplace=True 확인할 것

    MENU   PRICE   KCAL    원산지
0  아메리카노  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6     녹차  5300.0    0.0  코스타리카
7    NaN     NaN    NaN  코스타리카

In [638]:
# 결측값 채우기 (FutureWarning은 무시해도 된다.)
df['원산지'].fillna('코스타리카', inplace=True)
df

/tmp/ipykernel_13619/322007724.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카', inplace=True)

    MENU   PRICE   KCAL    원산지
0  아메리카노  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6     녹차  5300.0    0.0  코스타리카
7    NaN     NaN    NaN  코스타리카

In [639]:
df.to_csv("cafe3.csv", index=False)

In [640]:
## 원산지 값이 모두 추가된 cafe.csv를 cafe3.csv로 저장
df.to_csv('cafe3.csv', index=False) ## index는 저장하지 말 것 옵션: index=False

## Section13. 값 변경

In [641]:
# 데이터 확인
pd.read_csv("cafe3.csv")
df.head(3)

    MENU   PRICE   KCAL    원산지
0  아메리카노  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라

In [642]:
## 데이터 확인하기
pd.read_csv('cafe3.csv')
df.head()

    MENU   PRICE   KCAL    원산지
0  아메리카노  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카

In [643]:
## 기존 데이터에 있는 값을 변경할 것임 (replace를 옵션값이 아닌 함수로 적용)
df.replace('아메리카노', '룽고', inplace=True)
df.replace('녹차','그린티', inplace=True)
df ## 룽고 보단 아메리카노가 좋은데

    MENU   PRICE   KCAL    원산지
0     룽고  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6    그린티  5300.0    0.0  코스타리카
7    NaN     NaN    NaN  코스타리카

In [644]:
# 문자 변경 : 아메리카노 -> 룽고, 녹차 -> 그린티
df.replace('아메리카노', '룽고', inplace=True)
df.replace('녹차','그린티', inplace=True)
df

    MENU   PRICE   KCAL    원산지
0     룽고  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6    그린티  5300.0    0.0  코스타리카
7    NaN     NaN    NaN  코스타리카

In [645]:
change = {'룽고':'아메리카노', '그린티':'녹차'}
df.replace(change, inplace=True)
df

    MENU   PRICE   KCAL    원산지
0  아메리카노  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6     녹차  5300.0    0.0  코스타리카
7    NaN     NaN    NaN  코스타리카

In [646]:
## 조건을 넣어주는 방법을 사용할 수도 있음
change = {'룽고':'아메리카노', '그린티':'녹차'}
df.replace(change, inplace=True)
df

    MENU   PRICE   KCAL    원산지
0  아메리카노  4500.0   10.0   콜롬비아
1   카페라떼  5000.0  110.0  코스타리카
2   카페모카  5500.0  250.0   과테말라
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6     녹차  5300.0    0.0  코스타리카
7    NaN     NaN    NaN  코스타리카

In [647]:
### 아예 직접 명시하는 방법도 있음
df.loc[6, '원산지'] = '대한민국'  ## 국내산으로 변경 6번째 인덱스 메뉴
df.tail()

    MENU   PRICE   KCAL    원산지
3   카푸치노  5000.0  110.0   과테말라
4  에스프레소  4000.0   20.0  코스타리카
5    밀크티  5900.0  210.0  코스타리카
6     녹차  5300.0    0.0   대한민국
7    NaN     NaN    NaN  코스타리카

In [648]:
# loc로 값 변경하기
df.loc[6, '원산지'] = '대한민국'
df.tail(3)

  MENU   PRICE   KCAL    원산지
5  밀크티  5900.0  210.0  코스타리카
6   녹차  5300.0    0.0   대한민국
7  NaN     NaN    NaN  코스타리카

In [649]:
# 이벤트가 전체 1000으로 변경
df.loc[1:2, '이벤트가'] = 1000
df.head()

    MENU   PRICE   KCAL    원산지    이벤트가
0  아메리카노  4500.0   10.0   콜롬비아     NaN
1   카페라떼  5000.0  110.0  코스타리카  1000.0
2   카페모카  5500.0  250.0   과테말라  1000.0
3   카푸치노  5000.0  110.0   과테말라     NaN
4  에스프레소  4000.0   20.0  코스타리카     NaN

In [650]:
## 이벤트가 컬럼을 새로 추가하고 인덱스 1, 2 항목에만 1000으로 추가
df.loc[1:2, '이벤트가'] = 1000
df

    MENU   PRICE   KCAL    원산지    이벤트가
0  아메리카노  4500.0   10.0   콜롬비아     NaN
1   카페라떼  5000.0  110.0  코스타리카  1000.0
2   카페모카  5500.0  250.0   과테말라  1000.0
3   카푸치노  5000.0  110.0   과테말라     NaN
4  에스프레소  4000.0   20.0  코스타리카     NaN
5    밀크티  5900.0  210.0  코스타리카     NaN
6     녹차  5300.0    0.0   대한민국     NaN
7    NaN     NaN    NaN  코스타리카     NaN

In [651]:
## 작업물 저장
df.to_csv('cafe4.csv', index=False)

In [652]:
df.to_csv("cafe4.csv", index=False)

In [653]:
# map() 함수
import pandas as pd
df = pd.DataFrame({'만족도': ['만족', '보통' ,'불만', '보통', '만족']})

mapping = {'만족': 3, '보통': 2, '불만': 1}
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3

In [654]:
## 오 파이썬 할 때 map 하기 싫었는데
import pandas as pd
df = pd.DataFrame({'만족도': ['만족', '보통', '불만', '보통','만족']}) ## '만족도' 에 대한 값이 리스트 형식임
mapping = {'만족': 3, '보통' : 2, '불만' : 1}  #### key - value 기반으로 매핑됨
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3

## Section14. 문자열

In [655]:
import pandas as pd
df = pd.DataFrame({'A': ['데이터 분석', '기본 학습서', '퇴근 후 열공'],
                   'B': [10, 20, 30],
                   'C': ['ab cd', 'AB CD', 'ab cd ']
                   })
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [656]:
import pandas as pd
### 문자열 학습하기
df = pd.DataFrame({
    'A': ['데이터 분석','기본 학습서','퇴근 후 열공'], ## 현실에서의 '퇴근 후 열공'은 무척 어렵습니다. 진짜로.
    'B': [10, 20, 30],
    'C' : ['ab cd', 'AB CD' ,'ab cd ']
})
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [657]:
df['A'] = df['A'].replace('분석', '시각화')
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [658]:
## 'A'는 성의없으니께 다른 단어로 치환해볼게요
df['A'] = df['A'].replace('분석','시각화')
df  ## 오 왜 변한게 없을까요

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [659]:
df['A'] = df['A'].str.replace('분석', '시각화')
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [660]:
df['A'] = df['A'].str.replace('분석','시각화') ## 문자열 치환에는 df[]에 .str 로 문자열 임을 명시를 꼭 해줘야 함
df ## 변경 확인

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [661]:
df['B'] = df['B'].replace(10, 100)
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [662]:
## 그럼 숫자 데이터는 치환 시 str 여부가 어떻게 되는지
df['B'] = df['B'].replace(10, 100)
df ## 역시 str 없이 잘 치환되는 것을 확인할 수 있쥬

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [663]:
# 에러
# df['B'] = df['B'].str.replace(20, 200)
# print(df)

In [664]:
# 문자열 분리
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [665]:
## 문자열 분리하는 법에 대하여 알아보아요
df['A'].str.split()  ## .split() 에 아무런 기호, 값을 주지 않으면 띄어쓰기(공백) 기준으로 문자열을 분리해버려유

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [666]:
df['A'].str.split()[0] ## 첫 번째 행에 대해서만 분리를 시도해봐유
df['D'] = df['A'].str.split().str[0] ## 이름 'A'에 해당하는 항목의 첫번째 문자열 str[0]만 따서 'D'로 추가해줄게유 (데이터 항목에도 .str 필수)
df  ## 참 쉽쥬

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [667]:
df['A'].str.split()[0]

['데이터', '시각화']

In [668]:
df['D'] = df['A'].str.split().str[0]
df

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [669]:
# 문자 검색
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [670]:
## 특정 문자열을 포함하고 있는 데이터가 있는지 확인해유
df['A'].str.contains('기본') ## 문자열이니까 .str 추가하고 contains() 는 함수라서 ()로 묶음

0    False
1     True
2    False
Name: A, dtype: bool

In [671]:
## 확인하기 위해 새로운 컬럼으로 추가
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B       C    D  기본포함유무
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [672]:
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B       C    D  기본포함유무
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [673]:
menu = pd.Series(['맛난버거 세트', '매운 치킨버거', '더블 치즈버거'])
menu.isin(['맛난버거 세트', '더블 치즈버거'])

0     True
1    False
2     True
dtype: bool

In [674]:
menu = pd.Series(['맛난버거 세트', '매운 치킨버거' ,'더블 치즈버거'])
menu.isin(['맛난버거 세트','더블 치즈버거'])  ## 특정 문자열이 데이터에 존재하는지 확인

0     True
1    False
2     True
dtype: bool

In [675]:
## '세트' 메뉴가 있는지 확인
menu.str.contains('세트') ## contains() 쓰려면 str은 거의 필수

0     True
1    False
2    False
dtype: bool

In [676]:
menu.str.contains('세트')

0     True
1    False
2    False
dtype: bool

In [677]:
df['문자길이'] = df['A'].str.len()
df
## 문자길이 .str.len()
## 대문자 변환 .str.upper()
## 소문자 변환 .str.lower()

         A    B       C    D  기본포함유무  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [678]:
'AB cd' == 'ab CD'

False

In [679]:
df['C'] = df['C'].str.lower()
df['C']

0     ab cd
1     ab cd
2    ab cd
Name: C, dtype: object

In [680]:
df['C'] = df['C'].str.upper()
df['C']

0     AB CD
1     AB CD
2    AB CD
Name: C, dtype: object

In [681]:
df['C'] == 'AB CD'

0     True
1     True
2    False
Name: C, dtype: bool

In [682]:
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(" ","")  ## 공백 제거
df['C']

0    abcd
1    abcd
2    abcd
Name: C, dtype: object

In [683]:
df['C'].str[1:3]  ## C 항목의 두번째 값(인덱스 1)부터 세번째 값(인덱스 2)까지

0    bc
1    bc
2    bc
Name: C, dtype: object

In [684]:
df['C'][1:3]

1    abcd
2    abcd
Name: C, dtype: object

In [685]:
#### 우선 여기까지. 빅분기 실기 합격률 평균 적으면 40대~ 최대 60까지 나옴 ** 근데 난 빅분기가 싫어요

## Section15. 내장함수
- 데이터 핸들링을 위한 판다스 기초1(EDA) 부분에서 일부 내장함수를 학습했고, 그외 함수에 대해 살펴봄

In [686]:
df = pd.read_csv("cafe4.csv")
df.head(2)

    MENU   PRICE   KCAL    원산지    이벤트가
0  아메리카노  4500.0   10.0   콜롬비아     NaN
1   카페라떼  5000.0  110.0  코스타리카  1000.0

In [687]:
## 내장 함수
df = pd.read_csv('cafe4.csv') # 아까 만든 cafe4.csv 사용
df.head()

    MENU   PRICE   KCAL    원산지    이벤트가
0  아메리카노  4500.0   10.0   콜롬비아     NaN
1   카페라떼  5000.0  110.0  코스타리카  1000.0
2   카페모카  5500.0  250.0   과테말라  1000.0
3   카푸치노  5000.0  110.0   과테말라     NaN
4  에스프레소  4000.0   20.0  코스타리카     NaN

In [688]:
print(len(df))
print(df.shape[0])

8
8

In [689]:
## 데이터 프레임 길이 확인
print(len(df))
print(df.shape[0])  ## shape 값 = 행, 열 길이 확인 shape[0] = 행 길이 확인

8
8

In [690]:
cond = df['가격'] > 5000 ## 5000 보다 가격이 높은 메뉴

## 조건에 맞는 데이터의 *개수* 출력 -> sum()
print(sum(cond)) ## 3

## len() 함수로 조건에 맞는 개수 구하기
print(len(df[cond])) ## df[cond] : 조건에 맞는 데이터만 추림 | len(df[cond]) : 그렇게 추려낸 데이터의 개수

KeyError: '가격'

In [ ]:
df.sum(numeric_only=True)  ## numeric_only=True : 수치형 데이터만 사용, sum(numeric_only=True) : 수치형 데이터만 합계 계산

In [ ]:
cond = df['가격'] > 5000

#sum으로 조건에 맞는 개수 구하기
print(sum(cond))

#len으로 조건에 맞는 개수 구하기
print(len(df[cond]))

In [ ]:
df.sum(numeric_only=True)

In [ ]:
df.sum(axis=1, numeric_only=True) ## axis=1 열 기준(세로) 합계 계산

In [ ]:
df.sum(axis=1, numeric_only=True)

In [ ]:
print("최대값: ",df['가격'].max())
print("최소값: ",df['가격'].min())
print("평균값: ",df['가격'].mean())
print("중앙값: ",df['가격'].median())
print("합계: ",df['가격'].sum())
print("표준편차: ",df['가격'].std())
print("분산: ",df['가격'].var())

In [ ]:
## 연산 내장 함수 사용
print("최댓값: ", df['가격'].max())
print("최솟값: ", df['가격'].min())
print("평균값: ", df['가격'].mean())
print("중앙값: ", df['가격'].median())
print("합계: ", df['가격'].sum())
print("표준편차: ", df['가격'].std())
print("분산: ", df['가격'].var())   ## 표준편차 : std()  | 분산 : var()

In [ ]:
## 사분위수 내장함수  ** 이거 중요함 1번 문제 유형 출제
print("분위수 25% 값: ", df['가격'].quantile(.25))
print("분위수 75% 값: ", df['가격'].quantile(.75))
##### 사분위수 .quantile('.값') 25% = .25, 75% = .75

In [ ]:
# 분위수
print("분위수 25% 값", df['가격'].quantile(.25))
print("분위수 75% 값", df['가격'].quantile(.75))

In [ ]:
# 하위 25% 데이터
cond = df['가격'].quantile(.25) > df['가격']
df[cond]

In [ ]:
## 하위 25% 데이터
cond = df['가격'].quantile(.25) > df['가격']
## cond = df['가격'].quantile(.25) > df['가격'] ##손에 잘 안 익음 quantile()
df[cond]  ## 데이터의 '가격' 항목이 하위 25% 인 데이터

In [ ]:
## 가격 상위 25% 데이터
cond = df['가격'].quantile(.75) < df['가격']
df[cond]  ## 상위 25% = 분위수 75(.75) 보다 작.아.야 함  / 하위 25% = 분위수 25(.25) 보다 커.야. 함

In [ ]:
# 상위 25% 데이터
cond = df['가격'].quantile(.75) < df['가격']
df[cond]

In [ ]:
# 최빈값 구하기
df['원산지'].mode()[0]

In [ ]:
### 최빈값 내장함수
df['원산지'].mode()[0]
### '원산지' 항목에서 가장 많은 값 출력 (최빈값 : mode() 함수 사용)

In [ ]:
df['가격'].idxmax()   ## 가장 많은 값을 갖는 데이터의 레이블(index?) 출력
## 자매품으로 idxmin() 이 있음

In [ ]:
max_ind = df['가격'].idxmax()  ## 가격이 가장 값을 갖는 데이터의 레이블 값을 max_ind 변수에 저장
df.loc[max_ind] # loc[변수] 함수로 해당 데이터 검색

In [ ]:
df['가격'].idxmax()

In [ ]:
max_ind = df['가격'].idxmax()
df.loc[max_ind]

In [ ]:
# df.loc[max_ind, '메뉴'] # 추천 방법
df.loc[max_ind]['메뉴'] # 다른 방법

In [ ]:
## 최빈값 찾기
df.loc[max_ind]['메뉴'] ## 해당 메뉴의 이름 값 검색
df.nlargest(3, '가격')  ## 가격 값이 높은 3번째 값까지 출력 nlargest(3, '항목') - 가격이 비싼 3 메뉴 차례로 출력

In [ ]:
df.nlargest(3, '가격')

In [ ]:
## 반대로 낮은거 출력
df.nsmallest(2, '가격') ## '가격'이 낮은 데이터 2개를 순서대로 출력

In [ ]:
df.nsmallest(2, '가격')

In [691]:
# apply 적용해서 새로운 컬럼 생성 (칼로리 컬럼 활용)
def cal(x):
    if x >= 100:
        return "No"
    else:
        return "Yes"

df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

KeyError: '칼로리'

In [ ]:
### 함수 정의 : 새 컬럼 생성 - 칼로리 계산 : 100 이하 yes
def cal(x):
  if x >= 100:
    return "No"
  else:
    return "Yes"
df['먹어도 될까요'] = df['칼로리'].apply(cal)  ## apply() 함수 : 데이터프레임 값을 함수에 일괄 적용 - 함수를 변수로 넣어줌 | axis=0 OR axis=1을 옵션으로 추가 가능

In [692]:
import pandas as pd
df = pd.DataFrame({'Name': {0: '쿼카', 1: '알파카', 2: '시바견'},
                   '수학': {0: 90, 1: 93, 2: 85},
                   '영어': {0: 92, 1: 84, 2: 86},
                   '국어': {0: 91, 1: 94, 2: 83},})

df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [693]:
import pandas as pd
df = pd.DataFrame({
    'Name' : {0:'쿼카', 1:'알파카', 2:'시바견'},
    '수학': {0: 90, 1:93, 2:85},
    '영어' : {0: 92, 1:84, 2:86},
    '국어' : {0:91, 1:94, 2:83}
})
df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [694]:
pd.melt(df, id_vars=['Name']) ## melt() : 데이터 프레임 형식을 Wide에서 Long으로 변환하는데 사용 - 그냥 나열식으로 쭉 출력된다고 생각하면 됨

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [695]:
pd.melt(df, id_vars=['Name'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [696]:
pd.melt(df, id_vars=['Name'], value_vars=['수학', '영어'])  ## 옵션 값 : id_vars=['이름'] | value_vars['이름', '복수개 가능']

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86

In [697]:
pd.melt(df, id_vars=['Name'], value_vars=['수학', '영어'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86

In [698]:
pd.melt(df, id_vars=['Name'], var_name='과목', value_name='점수')

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86
6   쿼카  국어  91
7  알파카  국어  94
8  시바견  국어  83

In [699]:
pd.melt(df, id_vars=['Name'], var_name='과목', value_name='점수')  ## 이름 붙여줌. var_name : variable 이름 지정, value_name : value 이름 지정

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86
6   쿼카  국어  91
7  알파카  국어  94
8  시바견  국어  83

In [700]:
import pandas as pd

df = pd.DataFrame({
    "반": ["A반", "A반", "B반"],  # 반 정보 추가
    "이름": ["쿼카", "알파카", "시바견"],
    "수학": [90, 93, 85],
    "영어": [92, 84, 86],
    "국어": [91, 94, 83]
})
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  86  83

In [701]:
import pandas as pd
### '반' 항목 추가
df = pd.DataFrame({
    '반' : ["A반", "A반", "B반"], ## 리스트 자료형 안에 쌍 따옴표 권장 (이름 지정 시)
    "이름" : ["쿼카", "알파카","시바견"],
    "수학" : [90, 93, 85],
    "영어" : [92, 84, 85],
    "국어" : [91, 94, 83]
})
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  85  83

In [702]:
pd.melt(df, id_vars=["반", "이름"], var_name="과목", value_name="점수")

    반   이름  과목  점수
0  A반   쿼카  수학  90
1  A반  알파카  수학  93
2  B반  시바견  수학  85
3  A반   쿼카  영어  92
4  A반  알파카  영어  84
5  B반  시바견  영어  85
6  A반   쿼카  국어  91
7  A반  알파카  국어  94
8  B반  시바견  국어  83

## Section16. 그룹핑

In [703]:
### 그룹핑 하츄핑
df = pd.read_csv('cafe4.csv')  ## 엄청 전에 만든 cafe4
df.head()

    MENU   PRICE   KCAL    원산지    이벤트가
0  아메리카노  4500.0   10.0   콜롬비아     NaN
1   카페라떼  5000.0  110.0  코스타리카  1000.0
2   카페모카  5500.0  250.0   과테말라  1000.0
3   카푸치노  5000.0  110.0   과테말라     NaN
4  에스프레소  4000.0   20.0  코스타리카     NaN

In [704]:
df = pd.read_csv("cafe4.csv")
df.head(2)

    MENU   PRICE   KCAL    원산지    이벤트가
0  아메리카노  4500.0   10.0   콜롬비아     NaN
1   카페라떼  5000.0  110.0  코스타리카  1000.0

In [705]:
df.groupby(['원산지']).mean(numeric_only=True)
## '원산지' 기준으로 각 항목들 평균내기 (numeric_only=True : 수치형 데이터만 계산)

             PRICE        KCAL    이벤트가
원산지
과테말라   5250.000000  180.000000  1000.0
대한민국   5300.000000    0.000000     NaN
코스타리카  4966.666667  113.333333  1000.0
콜롬비아   4500.000000   10.000000     NaN

In [706]:
# 원두 기준, 평균
df.groupby(['원산지']).mean(numeric_only=True)

             PRICE        KCAL    이벤트가
원산지
과테말라   5250.000000  180.000000  1000.0
대한민국   5300.000000    0.000000     NaN
코스타리카  4966.666667  113.333333  1000.0
콜롬비아   4500.000000   10.000000     NaN

In [707]:
# 원두와 할인율 기준, 평균
df.groupby(['원산지', '칼로리']).mean(numeric_only=True)

KeyError: '칼로리'

In [708]:
### '원산지', '칼로리' 기준 평균 출력
df.groupby(['원산지','메뉴']).mean(numeric_only=True)  ## 오 이거 자료가 어떻게 된거임

KeyError: '메뉴'

In [709]:
df.groupby(['원산지', '메뉴']).agg(['mean', 'sum'])

KeyError: '메뉴'

In [710]:
df.groupby(['원산지','메뉴']).agg(['mean', 'sum'])   ## 모든 열에 대해 연산을 중첩해서 사용할 수 있음 "다중 집계" 함수 (mean으로 평균, sum으로 합계 동시 집계)

KeyError: '메뉴'

In [711]:
# 1개 인덱스 형태로 리셋
df.groupby(['원산지', '칼로리']).mean(numeric_only=True).reset_index()

KeyError: '칼로리'

In [712]:
df.groupby(['원산지','칼로리']).mean(numeric_only=True).reset_index()
### '원산지', '칼로리' 기준으로 mean(수치형 데이터만) 평균 계산 / .reset_index() : 현재 값 기준으로 인덱스 다시 설정

KeyError: '칼로리'

In [713]:
# transform
import pandas as pd

# 데이터 생성 (일부 결측값 포함)
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [714]:
import pandas as pd

## 데이터 생성
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리','딸기','블루베리'],
    '가격' : [1000, None, 1500, None, 2000, 2500, None, 1800]  ## 결측값을 포함하는 데이터 프레임 생성
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [715]:
### groupby() 함수 사용시 () <- 괄호로 꼭 묶고 사용해야 함
price = df.groupby('과일')['가격'].transform("mean")  ## '과일'을 그룹화하여 '가격' 항목의 "평균" 값을 출력 | transform() : 행, 열 개수 맞춰서 변환 -> 출력 값은 가격의 평균(과일로 그룹화 된)
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [716]:
##### 이거 1번 문제 유형 : 과일 '가격'의 결측값을 각 과일의 평균값으로 대치
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [717]:
price = df.groupby('과일')['가격'].transform("mean")
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [718]:
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [719]:
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '등급': ['B', 'B', 'A', 'A', 'A', 'A', 'B', 'B'],  # 새로운 그룹 추가
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [720]:
## 데이터 프레임 생성
df = pd.DataFrame({
    '과일' : ['딸기','블루베리','딸기','블루베리','딸기','블루베리','딸기','블루베리'],
    '등급' : ['B','B','A','A','A','A','B','B'],
    '가격' : [1000, None, 1500, None, 2000, 2500, None, 1800]  ## 마찬가지로 결측값을 포함하는 데이터
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [721]:
## '과일'와 '등급'으로 그룹지은 '가격'의 '평균'값 출력(transform : 행, 열 맞춤)
price = df.groupby(['과일','등급'])['가격'].transform("mean") ## 그룹화 조건에 항목 값 붙일때 . 없이 고대로 붙이기
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [722]:
price = df.groupby(['과일', '등급'])['가격'].transform("mean")
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [723]:
df['가격'] = df['가격'].fillna(price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [724]:
df['가격'] = df['가격'].fillna(price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [725]:
# unstack
import pandas as pd

coffee_data = {
    '커피종류': ['아메리카노', '아메리카노', '아메리카노', '라떼', '라떼', '라떼'],
    '컵크기': ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Large'],
    '판매량': [120, 150, 200, 100, 130, 180]
}
df = pd.DataFrame(coffee_data)
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [765]:
### 그룹핑 내용 드릅게 많네
import pandas as pd
coffee_data = {
   '커피종류' : ['아메리카노','아메리카노','아메리카노','라떼','라떼','라떼'],
   '컵크기' : ['Small','Medium','Large','Small','Medium','Large'] ,
   '판매량' : [120, 150, 200, 100, 130, 180]
}
df = pd.DataFrame(coffee_data)
df
####  데이터 프레임 직접 생성 = ({}) 이중 괄호 / 데이터 -> 데이터 프레임 = 변수값에 데이터 저장 후 pd.DataFrame(변수) 형태로 변환

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [766]:
# groupby 적용
grouped = df.groupby(['커피종류', '컵크기'])['판매량'].sum()
grouped

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [767]:
### '커피종류' 및 '컵크기' 기준으로 그룹화 하여 판매량의 합계 출력
grouped = df.groupby(['커피종류', '컵크기'])['판매량'].sum()
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [771]:
### 인덱스 level별 컬럼 올려주는 역할   '라떼' 메뉴의 판매량 순위 Large - Medium - Small '아메리카노' 동일하게 순서대로 출력
grouped.unstack()  ## '컵크기'를 컬럼으로 사용

컵크기    Large  Medium  Small
커피종류
라떼       180     130    100
아메리카노    200     150    120

In [773]:
grouped.unstack(level=0) ## 행-열 교체 / '커피종류'를 컬럼으로 사용

커피종류     라떼  아메리카노
컵크기
Large   180    200
Medium  130    150
Small   100    120

In [729]:
# 컵크기를 컬럼으로 변환
grouped.unstack()

컵크기    Large  Medium  Small
커피종류
라떼       180     130    100
아메리카노    200     150    120

In [730]:
# 커피종류를 컬럼으로 변환
grouped.unstack(level=0)

커피종류     라떼  아메리카노
컵크기
Large   180    200
Medium  130    150
Small   100    120

In [775]:
### unstack() 이중 사용
grouped.unstack().unstack()
## '컵크기' '커피종류' 구분 후 공백 컬럼 존재 > 값 출력 됨

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

In [731]:
# 두 번의 unstack 적용
grouped.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

In [776]:
## 뭐이리 많음

## Section17. 시계열 데이터 (Datetime)

In [732]:
import pandas as pd
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
    'DateTime1': ['24-02-17 13:45:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
    'DateTime2': ['2024-02-17 13-45-30', '2024-02-18 14-55-45', '2024-02-19 15-30-15', '2024-02-20 16-10-50'],
    'DateTime3': ['02/17/2024 01:45:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
    'DateTime4': ['17 Feb 2024 13:45:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50']
}

df = pd.DataFrame(data)
df.to_csv("date_data.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:45:30,2024-02-17 13-45-30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14-55-45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15-30-15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16-10-50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [780]:
import pandas as  pd
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
    'DateTime1': ['24-02-17 13:45:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
    'DateTime2': ['2024-02-17 13-45-30', '2024-02-18 14-55-45', '2024-02-19 15-30-15', '2024-02-20 16-10-50'],
    'DateTime3': ['02/17/2024 01:45:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
    'DateTime4': ['17 Feb 2024 13:45:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50']
}

df = pd.DataFrame(data)
df.to_csv('date_data.csv', index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:45:30,2024-02-17 13-45-30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14-55-45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15-30-15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16-10-50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [782]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
count,4,4,4,4,4,4,4,4,4
unique,4,4,4,4,4,4,4,4,4
top,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:45:30,2024-02-17 13-45-30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30
freq,1,1,1,1,1,1,1,1,1

In [733]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [734]:
df = pd.read_csv("date_data.csv")
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'])
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
df

/tmp/ipykernel_13619/2722885956.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])
/tmp/ipykernel_13619/2722885956.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime1'] = pd.to_datetime(df['DateTime1'])
/tmp/ipykernel_13619/2722885956.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime3'] = pd.to_datetime(df['DateTime3'])

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2017-02-24 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2018-02-24 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2019-02-24 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2020-02-24 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50

In [788]:
df = pd.read_csv("date_data.csv")
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'])
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
df   ## 시계열 데이터 to_datetime() 함수 사용 -> 날짜 데이터로 형식 변환

/tmp/ipykernel_13619/743503231.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])
/tmp/ipykernel_13619/743503231.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime1'] = pd.to_datetime(df['DateTime1'])
/tmp/ipykernel_13619/743503231.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime3'] = pd.to_datetime(df['DateTime3'])

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2017-02-24 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2018-02-24 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2019-02-24 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2020-02-24 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50

In [790]:
df = pd.read_csv("date_data.csv")
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'], format='%y/%m/%d')
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format='%y-%m-%d %H:%M:%S')
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df[['Date2', 'Date3', 'DateTime1', 'DateTime2']]
## to_datetiem(df['항목'], format='%Y:%m:%d') ->  날짜 형식 지정

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [794]:
cols = ['Date2', 'Date3', 'DateTime1', 'DateTime2']  ## 컬럼명 지정
df[cols]  ## 데이터 프레임에 적용
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: datetime64[ns](4), object(5)
memory usage: 420.0+ bytes

In [736]:
cols = ['Date2', 'Date3', 'DateTime1', 'DateTime2']
df[cols]

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [737]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: datetime64[ns](4), object(5)
memory usage: 420.0+ bytes

In [738]:
df['year'] = df['DateTime1'].dt.year
df['month'] = df['DateTime1'].dt.month
df['day'] = df['DateTime1'].dt.day
df['hour'] = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,second
0,2024-02-17,2024-02-17,2024-02-17,02/17/2024,17-Feb-2024,2024-02-17 13:45:30,2024-02-17 13:45:30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30,2024,2,17,13,45,30
1,2024-02-18,2024-02-18,2024-02-18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18 14:55:45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45,2024,2,18,14,55,45
2,2024-02-19,2024-02-19,2024-02-19,02/19/2024,19-Feb-2024,2024-02-19 15:30:15,2024-02-19 15:30:15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15,2024,2,19,15,30,15
3,2024-02-20,2024-02-20,2024-02-20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20 16:10:50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50,2024,2,20,16,10,50

In [798]:
df['year'] = df['DateTime1'].dt.year
df['month'] = df['DateTime1'].dt.month
df['day'] = df['DateTime1'].dt.day
df['hour'] = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,second
0,2024-02-17,2024-02-17,2024-02-17,02/17/2024,17-Feb-2024,2024-02-17 13:45:30,2024-02-17 13:45:30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30,2024,2,17,13,45,30
1,2024-02-18,2024-02-18,2024-02-18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18 14:55:45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45,2024,2,18,14,55,45
2,2024-02-19,2024-02-19,2024-02-19,02/19/2024,19-Feb-2024,2024-02-19 15:30:15,2024-02-19 15:30:15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15,2024,2,19,15,30,15
3,2024-02-20,2024-02-20,2024-02-20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20 16:10:50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50,2024,2,20,16,10,50

In [800]:
df['DateTime1'].dt.dayofweek   ### 일주일을 1-7에 해당하는 숫자로 표현하며 해당되는 숫자 반환

0    5
1    6
2    0
3    1
Name: DateTime1, dtype: int32

In [739]:
df['DateTime1'].dt.dayofweek

0    5
1    6
2    0
3    1
Name: DateTime1, dtype: int32

In [740]:
print(df['DateTime1'].dt.to_period('Y'))
print(df['DateTime1'].dt.to_period('Q'))
print(df['DateTime1'].dt.to_period('M'))
print(df['DateTime1'].dt.to_period('D'))
print(df['DateTime1'].dt.to_period('H'))

0    2024
1    2024
2    2024
3    2024
Name: DateTime1, dtype: period[Y-DEC]
0    2024Q1
1    2024Q1
2    2024Q1
3    2024Q1
Name: DateTime1, dtype: period[Q-DEC]
0    2024-02
1    2024-02
2    2024-02
3    2024-02
Name: DateTime1, dtype: period[M]
0    2024-02-17
1    2024-02-18
2    2024-02-19
3    2024-02-20
Name: DateTime1, dtype: period[D]
0    2024-02-17 13:00
1    2024-02-18 14:00
2    2024-02-19 15:00
3    2024-02-20 16:00
Name: DateTime1, dtype: period[h]

/tmp/ipykernel_13619/2095775091.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  print(df['DateTime1'].dt.to_period('H'))

In [803]:
print(df['DateTime1'].dt.to_period('Y'))
print(df['DateTime1'].dt.to_period('Q'))
print(df['DateTime1'].dt.to_period('M'))
print(df['DateTime1'].dt.to_period('D'))
print(df['DateTime1'].dt.to_period('H'))
### .to_period() 특정 날짜를 기간 단위로 변환

0    2024
1    2024
2    2024
3    2024
Name: DateTime1, dtype: period[Y-DEC]
0    2024Q1
1    2024Q1
2    2024Q1
3    2024Q1
Name: DateTime1, dtype: period[Q-DEC]
0    2024-02
1    2024-02
2    2024-02
3    2024-02
Name: DateTime1, dtype: period[M]
0    2024-02-17
1    2024-02-18
2    2024-02-19
3    2024-02-20
Name: DateTime1, dtype: period[D]
0    2024-02-17 13:00
1    2024-02-18 14:00
2    2024-02-19 15:00
3    2024-02-20 16:00
Name: DateTime1, dtype: period[h]

/tmp/ipykernel_13619/4237764950.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  print(df['DateTime1'].dt.to_period('H'))

## Section18. 시계열 데이터 (Timedelta)

In [741]:
df = pd.read_csv("date_data.csv", usecols=['DateTime4'], parse_dates=['DateTime4'])
df

            DateTime4
0 2024-02-17 13:45:30
1 2024-02-18 14:55:45
2 2024-02-19 15:30:15
3 2024-02-20 16:10:50

In [807]:
df = pd.read_csv('date_data.csv', usecols=['DateTime4'], parse_dates=['DateTime4'])  ## usecols=[] 특정 열만 가져옴  / parse_dates[] 날짜 형식의 데이터를 datetime 형식으로 변환
df

            DateTime4
0 2024-02-17 13:45:30
1 2024-02-18 14:55:45
2 2024-02-19 15:30:15
3 2024-02-20 16:10:50

In [742]:
day = pd.Timedelta(days=99)
df['100day'] = df['DateTime4'] + day
df

            DateTime4              100day
0 2024-02-17 13:45:30 2024-05-26 13:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50

In [810]:
day = pd.Timedelta(days=99)   ## .Timedelta : 시간 간격을 계산 할 때 사용
df['100day'] = df['DateTime4'] + day   ## DateTime4 항목의 값에 99일을 더해 100일 후의 값을 출력함
df

            DateTime4              100day
0 2024-02-17 13:45:30 2024-05-26 13:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50

In [743]:
hour = pd.Timedelta(hours=100)
df['100hour'] = df['DateTime4'] + hour
df

            DateTime4              100day             100hour
0 2024-02-17 13:45:30 2024-05-26 13:45:30 2024-02-21 17:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45 2024-02-22 18:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15 2024-02-23 19:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50 2024-02-24 20:10:50

In [813]:
hour = pd.Timedelta(hours=100) ## hours=100 으로 100시간 계산
df['100hour'] = df['DateTime4'] + hour  ### DateTime4 값에 100 시간을 더하여 100시간 후의 시간 계산
df   ## Timedelta() 함수는 시간 계산 하는 데 사용하는 함수

            DateTime4              100day             100hour
0 2024-02-17 13:45:30 2024-05-26 13:45:30 2024-02-21 17:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45 2024-02-22 18:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15 2024-02-23 19:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50 2024-02-24 20:10:50

In [744]:
difference = pd.Timedelta(weeks=7, days=7, hours=7, minutes=7, seconds=7)
df['difference'] = df['DateTime4'] - difference
df

,DateTime4,100day,100hour,difference
0,2024-02-17 13:45:30,2024-05-26 13:45:30,2024-02-21 17:45:30,2023-12-23 06:38:23
1,2024-02-18 14:55:45,2024-05-27 14:55:45,2024-02-22 18:55:45,2023-12-24 07:48:38
2,2024-02-19 15:30:15,2024-05-28 15:30:15,2024-02-23 19:30:15,2023-12-25 08:23:08
3,2024-02-20 16:10:50,2024-05-29 16:10:50,2024-02-24 20:10:50,2023-12-26 09:03:43

In [818]:
difference = pd.Timedelta(weeks=7, days=7, hours=7, minutes=7, seconds=7) ## Timedelta 사용시 pd. 에서 불러오는 거 | 시간 다중 지정
df['difference'] = df['DateTime4'] - difference
df

,DateTime4,100day,100hour,difference
0,2024-02-17 13:45:30,2024-05-26 13:45:30,2024-02-21 17:45:30,2023-12-23 06:38:23
1,2024-02-18 14:55:45,2024-05-27 14:55:45,2024-02-22 18:55:45,2023-12-24 07:48:38
2,2024-02-19 15:30:15,2024-05-28 15:30:15,2024-02-23 19:30:15,2023-12-25 08:23:08
3,2024-02-20 16:10:50,2024-05-29 16:10:50,2024-02-24 20:10:50,2023-12-26 09:03:43

In [820]:
diff = df['100hour'] - df['difference']  ## 날짜 연산 수행 전 to_datetiem(df['DateTime4']) 필수 수행
diff

0   60 days 11:07:07
1   60 days 11:07:07
2   60 days 11:07:07
3   60 days 11:07:07
dtype: timedelta64[ns]

In [819]:
diff = df['100hour'] - df['difference']
diff

0   60 days 11:07:07
1   60 days 11:07:07
2   60 days 11:07:07
3   60 days 11:07:07
dtype: timedelta64[ns]

In [821]:
print(diff.dt.total_seconds()) # 초
print(diff.dt.total_seconds()/60) # 분
print(diff.dt.total_seconds()/60/60) # 시간
print(diff.dt.total_seconds()/60/60/24) # 일
### 이거 문제 출제 안 될 거 같은데

0    5224027.0
1    5224027.0
2    5224027.0
3    5224027.0
dtype: float64
0    87067.116667
1    87067.116667
2    87067.116667
3    87067.116667
dtype: float64
0    1451.118611
1    1451.118611
2    1451.118611
3    1451.118611
dtype: float64
0    60.463275
1    60.463275
2    60.463275
3    60.463275
dtype: float64

In [747]:
print(diff.dt.days)
print(diff.dt.seconds)

0    60
1    60
2    60
3    60
dtype: int64
0    40027
1    40027
2    40027
3    40027
dtype: int32

In [823]:
print(diff.dt.days)
print(diff.dt.seconds)

0    60
1    60
2    60
3    60
dtype: int64
0    40027
1    40027
2    40027
3    40027
dtype: int32

In [748]:
min = 5.41
print(int(min), "분")
print(0.41*60, "초")

5 분
24.599999999999998 초

In [825]:
min = 5.41
print(int(min), "분") # 정수형으로 5.41 초 계산
print(0.41 * 60, "초")

5 분
24.599999999999998 초

In [829]:
print(round(diff.dt.total_seconds()/60)) ## total_seconds로 모든 초 합계 /60 하여 평균 출력

0    87067.0
1    87067.0
2    87067.0
3    87067.0
dtype: float64

In [749]:
print(round(diff.dt.total_seconds()/60))

0    87067.0
1    87067.0
2    87067.0
3    87067.0
dtype: float64

In [830]:
#### 시계열 데이터 쉽지 않네.

## Section19. 데이터 합치기

In [750]:
import pandas as pd

# 에피타이저 메뉴
appetizer = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Bread'],
    'Price': [5000, 3000, 2000]
})

# 메인 메뉴
main = pd.DataFrame({
    'Menu': ['Steak', 'Pasta', 'Chicken'],
    'Price': [15000, 12000, 10000]
})
print(appetizer)
print(main)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000
      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [751]:
# 두 메뉴를 수직으로 연결
full_menu = pd.concat([appetizer, main], ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [752]:
# 두 메뉴를 좌우로 연결
full_menu = pd.concat([appetizer, main], axis=1)
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [753]:
# 메뉴와 가격
price = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Steak', 'Pasta'],
    'Price': [5000, 3000, 15000, 12000]
})

# 메뉴와 칼로리
cal = pd.DataFrame({
    'Menu': ['Soup', 'Steak', 'Pasta','Salad'],
    'Calories': [100, 500, 400, 150]
})

# 두 데이터프레임을 'Menu'를 기준으로 병합
menu_info = pd.merge(price, cal, on='Menu')
menu_info

    Menu  Price  Calories
0  Salad   5000       150
1   Soup   3000       100
2  Steak  15000       500
3  Pasta  12000       400

## Section20.피벗테이블

In [754]:
import pandas as pd

# 직원별 부서 및 급여 정보
data = {
    '이름': ['서아', '다인', '채아', '예담', '종현', '태헌'],
    '부서': ['개발', '기획', '개발', '기획', '개발', '기획'],
    '급여': [3000, 3200, 3100, 3300, 2900, 3100]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서별 평균 급여 계산
pt = df.pivot_table(index='부서', values='급여', aggfunc='mean')
print("\n[부서별 평균 급여]") #\n은 줄 바꿈(새로운 줄 시작)
print(pt)

[원본 데이터]
   이름  부서    급여
0  서아  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

[부서별 평균 급여]
        급여
부서
개발  3000.0
기획  3200.0

In [755]:
# 부서와 직급별 급여 정보
data = {
    '부서': ['개발', '기획', '기획', '기획', '개발', '개발'],
    '직급': ['대리', '과장', '대리', '과장', '대리', '과장'],
    '급여': [3000, 4000, 3200, 4200, 3500, 4500]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 직급별 급여 합계 계산
pt = df.pivot_table(index='부서', columns='직급', values='급여', aggfunc='sum')
print("\n[부서 및 직급별 급여 합계]")
print(pt)

[원본 데이터]
   부서  직급    급여
0  개발  대리  3000
1  기획  과장  4000
2  기획  대리  3200
3  기획  과장  4200
4  개발  대리  3500
5  개발  과장  4500

[부서 및 직급별 급여 합계]
직급    과장    대리
부서
개발  4500  6500
기획  8200  3200

In [756]:
# 부서와 성별, 근속연수 정보
data = {
    '부서': ['개발', '기획', '기획', '기획', '개발', '개발'],
    '성별': ['남', '여', '남', '여', '남', '여'],
    '근속연수': [3, 5, 4, 6, 7, 8]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 성별 평균 근속연수 계산
pt = df.pivot_table(index='부서', columns='성별', values='근속연수', aggfunc='mean')
print("\n[부서 및 성별 평균 근속연수]")
print(pt)

[원본 데이터]
   부서 성별  근속연수
0  개발  남     3
1  기획  여     5
2  기획  남     4
3  기획  여     6
4  개발  남     7
5  개발  여     8

[부서 및 성별 평균 근속연수]
성별    남    여
부서
개발  5.0  8.0
기획  4.0  5.5

In [757]:
# 다양한 집계를 위한 데이터셋
import pandas as pd

df = pd.DataFrame({
    "구분": ["전자", "전자", "전자", "전자", "전자", "가전", "가전", "가전", "가전"],
    "유형": ["일반", "일반", "일반", "특수", "특수", "일반", "일반", "특수", "특수"],
    "크기": ["소형", "대형", "대형", "소형", "소형", "대형", "소형", "소형", "대형"],
    "수량": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    "금액": [2, 4, 5, 5, 6, 6, 8, 9, 9]
})
print(df)

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [758]:
# 단일 값에 대해 집계
pt = pd.pivot_table(
    df,
    values='수량',
    index=['구분', '유형'],
    columns=['크기'],
    aggfunc="sum"
)
pt

크기      대형   소형
구분 유형
가전 일반  4.0  5.0
   특수  7.0  6.0
전자 일반  4.0  1.0
   특수  NaN  6.0

In [759]:
# 단일 값에 대해 집계 (누락 값 0 처리)
pt = pd.pivot_table(
    df,
    values='수량',
    index=['구분', '유형'],
    columns=['크기'],
    aggfunc="sum",
    fill_value=0
)
pt

크기     대형  소형
구분 유형
가전 일반   4   5
   특수   7   6
전자 일반   4   1
   특수   0   6

In [760]:
# 여러 열에 대해 각기 다른 집계 함수 적용
pt = pd.pivot_table(
    df,
    values=['수량', '금액'],
    index=['구분', '크기'],
    aggfunc={'수량': "mean", '금액': "mean"}
)
pt

             금액        수량
구분 크기
가전 대형  7.500000  5.500000
   소형  8.500000  5.500000
전자 대형  4.500000  2.000000
   소형  4.333333  2.333333

In [761]:
# 하나의 열에 대해 여러 집계 함수를 동시에 적용
pt = pd.pivot_table(
    df,
    values=['수량', '금액'],
    index=['구분', '크기'],
    aggfunc={'수량': "mean", '금액': ["min", "max", "mean"]}
)
pt

       금액                      수량
      max      mean min      mean
구분 크기
가전 대형   9  7.500000   6  5.500000
   소형   9  8.500000   8  5.500000
전자 대형   5  4.500000   4  2.000000
   소형   6  4.333333   2  2.333333

In [762]:
pt.reset_index()

   구분  크기  금액                      수량
          max      mean min      mean
0  가전  대형   9  7.500000   6  5.500000
1  가전  소형   9  8.500000   8  5.500000
2  전자  대형   5  4.500000   4  2.000000
3  전자  소형   6  4.333333   2  2.333333

## Section21.Quiz

In [763]:
# 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '에스프레소', '카페모카', '바닐라라떼'],
    "가격":[4500, 5000, 4000, 5900, 5300],
    "칼로리":[10, 110, np.NaN, 210, np.NaN],
    "원산지":['과테말라','브라질','과테말라', np.NaN, np.NaN]
})
df

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

**1. '칼로리' 컬럼 결측치는 칼로리 데이터 중 최소값으로 결측치를 채우시오**

In [ ]:
min_cal = df['칼로리'].min()
df['칼로리'] = df['칼로리'].fillna(min_cal)
df

**2. '원산지' 컬럼 결측치는 원두 데이터 중 최빈값으로 결측치를 채우시오**

In [ ]:
f = df['원산지'].mode()[0]
df['원산지'] = df['원산지'].fillna(f)
df

**3. 가격이 5000 이상인 데이터의 수를 구하시오**

In [ ]:
cond = df['가격'] >= 5000
len(df[cond]) # 또는 sum(cond)

**4. ’이벤트가’ 컬럼을 만들고 기존 가격에서 50% 할인된 가격을 채우시오**

In [ ]:
df['이벤트가'] = df['가격'] * 0.5
df

**5. '칼로리' 컬럼을 삭제하시오**
-

In [ ]:
df = df.drop('칼로리', axis=1)
df

**6. 앞에서부터 3개의 데이터만 선택하시오(loc 활용)**

In [ ]:
df.loc[:2]

**7. 앞에서부터 3개의 데이터만 선택하시오(iloc 활용)**

In [ ]:
df.iloc[:3]

**8. 주어진 데이터(df)에서 아래 값을 loc를 활용해 데이터 프레임으로 출력하시오**
- 카페라떼	5000
- 에스프레소 4000

In [ ]:
# loc
df.loc[1:2, :'가격']

**9. 주어진 데이터(df)에서 아래 값을 iloc를 활용해 데이터 프레임으로 출력하시오**
- 카페라떼	5000
- 에스프레소 4000

In [ ]:
# iloc
df.iloc[1:3, :2]

**10. 메뉴 중 가격이 가장 비싼 순으로 정렬해 상위 3개 값을 구하시오**

In [ ]:
df = df.sort_values('가격', ascending=False)
df.iloc[:3]