<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/ch2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part1/ch2/ch2_pandas.ipynb)

# 판다스

## Section1. 데이터프레임과 시리즈

In [14]:
# 판다스 라이브러리 불러오기
import pandas as pd

In [15]:
import pandas as pd

In [16]:
menu = pd.Series(['비빔밥','김치찌개', '된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [17]:
# 시리즈 만들기 (문자열)
menu = pd.Series(['비빔밥', '김치찌개', '된장찌개','청국장'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
3     청국장
dtype: object

In [18]:
# 시리즈 만들기(정수형)
price = pd.Series([10000, 9000, 8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [19]:
total = pd.Series([10000, 20000, 30000, 50000])
total

0    10000
1    20000
2    30000
3    50000
dtype: int64

In [195]:
pd.DataFrame({
    '메뉴' : menu,
    '가격' : total
})

        메뉴     가격
0  맛난버거 세트  10000
1  매운 치킨버거  20000
2  더블 치즈버거  30000
3      NaN  50000

In [21]:
# 데이터 프레임 만들기 pd.DataFrame({"컬럼명":데이터})
pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

     메뉴       가격
0   비빔밥  10000.0
1  김치찌개   9000.0
2  된장찌개   8000.0
3   청국장      NaN

In [22]:
# 데이터 프레임 만들기 pd.DataFrame({"컬럼명":데이터})
df = pd.DataFrame({
    "메뉴":['비빔밥', '김치찌개', '된장찌개'],
    "가격":[10000, 9000, 8000],
    "원산지":['국내산', '국내산', '국내산']
})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [23]:
df = pd.DataFrame({
    'MENU':['비빔밥','계란후라이','계란말이','스크램블'],
    'PRICE':[10000, 4000, 50000, 120000],
    '원산지':['국내산','외국산','칠레산','호주산']
})
df

    MENU   PRICE  원산지
0    비빔밥   10000  국내산
1  계란후라이    4000  외국산
2   계란말이   50000  칠레산
3   스크램블  120000  호주산

In [24]:
## 시리즈 선택
df['MENU']
df['PRICE']

0     10000
1      4000
2     50000
3    120000
Name: PRICE, dtype: int64

In [25]:
# 시리즈 선택 (가격)
df['메뉴']

KeyError: '메뉴'

In [ ]:
# 데이터프레임 선택 (가격)
df[['메뉴']]

In [ ]:
df[['MENU','PRICE']]

In [ ]:
df[['메뉴', '가격']]

In [ ]:
# 데이터프레임 선택 (가격)
cols = ['메뉴', '가격']
df[cols]

In [ ]:
## 하나로 합치기
cols = ['MENU','PRICE']
df[cols]

In [26]:
## 데이터 프레임 type 확인
print("df       : ", type(df))
print("df['price']       : ", type(df['PRICE']))
print("df[['price']]       : ", type(df[['PRICE']]))

df       :  <class 'pandas.core.frame.DataFrame'>
df['price']       :  <class 'pandas.core.series.Series'>
df[['price']]       :  <class 'pandas.core.frame.DataFrame'>

In [27]:
# 데이터 프레임 type 확인
print("df          : ", type(df))
print("df['가격']   : ", type(df['가격']))
print("df[['가격']] : ", type(df[['가격']]))

df          :  <class 'pandas.core.frame.DataFrame'>

KeyError: '가격'

In [196]:
## 데이터 준비
df = pd.DataFrame({
    "MENU" : ['아메리카노','카페라떼','카푸치노','카페모카','밀크티','녹차','말차'],
    "PRICE" : [4000, 4500, 4400, 4700, 5200, 2000, 4000],
    "KCAL" : [10, 110, 270, 300, 320, 20, 30]
})
df

    MENU  PRICE  KCAL
0  아메리카노   4000    10
1   카페라떼   4500   110
2   카푸치노   4400   270
3   카페모카   4700   300
4    밀크티   5200   320
5     녹차   2000    20
6     말차   4000    30

In [197]:
## .csv 파일로 만들어서 저장 및 확인
df.to_csv('tea.csv')  ## to_csv() 함수 사용 '이름'
tea_df = pd.read_csv('tea.csv') ## df로 저장 pd.read_csv(만든.csv)
tea_df.head()

   Unnamed: 0   MENU  PRICE  KCAL
0           0  아메리카노   4000    10
1           1   카페라떼   4500   110
2           2   카푸치노   4400   270
3           3   카페모카   4700   300
4           4    밀크티   5200   320

## Section2. 데이터 저장 및 불러오기

In [28]:
# 데이터 준비
df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리":[10, 110, 250, 110, 20, 210, 0],
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [29]:
df.to_csv('temp.csv')

In [30]:
temp_df = pd.read_csv('temp.csv')
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [31]:
# 데이터 불러오기
df.to_csv('cafe.csv', index=False)
df = pd.read_csv('cafe.csv')
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

## Section3. 탐색적 데이터 분석(EDA)

In [32]:
# 데이터 샘플 확인: 앞에서 부터 n개 (기본 5개)
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [33]:
df.head(2)
df.tail(5)

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [34]:
# 데이터 샘플 확인: 뒤에서 부터 n개 (기본 5개)
df.tail(3)

      메뉴    가격  칼로리
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [35]:
df.sample(3)

     메뉴    가격  칼로리
6    녹차  5300    0
1  카페라떼  5000  110
3  카푸치노  5000  110

In [36]:
df.sample(5)

      메뉴    가격  칼로리
6     녹차  5300    0
4  에스프레소  4000   20
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

In [200]:
df.shape ## 데이터 프레임 크기 (행, 컬럼) 개수

(7, 3)

In [201]:
df.info() ## index Column_name Non_Null type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      int64
 2   KCAL    7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [37]:
# 데이터 프레임 크기 (행, 컬럼)
df.shape

(7, 3)

In [38]:
# 컬럼 형태(type)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [39]:
# 상관관계
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [205]:
### 상관관계 출력
df.corr(numeric_only=True)
df.corr(numeric_only=True) ## df.corr(numeric_only=True) 손에 안 익는다ㅏ

          PRICE      KCAL
PRICE  1.000000  0.693084
KCAL   0.693084  1.000000

In [40]:
# 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car":['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    "size":['S','M','S','S','M','M','L','S','S', 'M','S']
})
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [208]:
## 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car" : ['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    "size" : ['S', 'M', 'S', 'S','M','M','L','S','S','M','S']
}) ## 두 항목의 길이가 같아야 함

In [211]:
df_car.nunique() ## unique X nunique O (중복되지 않는 데이터 수)

car     2
size    3
dtype: int64

In [41]:
# 항목 종류 수
df_car.nunique()

car     2
size    3
dtype: int64

In [42]:
# 항목 종류
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [213]:
## 항목 종류 (중복되지 않는 데이터)
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [215]:
print(df_car['car'].value_counts()) ## 항목 별 개수 계산
print(df_car['size'].value_counts()) ## 데이터프레임['항목'].value_counts() count에 s붙이기

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [217]:
# 항목별 개수
print(df_car['car'].value_counts())
print(df_car['size'].value_counts())
df.describe() ### col 개수, 평균, std, 최소 최대, 4분위수

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

             PRICE        KCAL
count     7.000000    7.000000
mean   4114.285714  151.428571
std    1020.504077  140.407570
min    2000.000000   10.000000
25%    4000.000000   25.000000
50%    4400.000000  110.000000
75%    4600.000000  285.000000
max    5200.000000  320.000000

In [44]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [220]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [222]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [225]:
df.describe(include="O")

         MENU
count       7
unique      7
top     아메리카노
freq        1

## Section4. 자료형 변환

In [47]:
# 데이터 준비
data = {
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리":['10', '110', '250', '110', '20', '210', '0'],
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [229]:
### 데이터 생성
data = {
    "MENU":['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    "PRICE":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "KCAL":['10','110','250','110','20','210','0']
}
df = pd.DataFrame(data)
df.info() ## Non-Null Count 개수가 3개 모두 동일한 지 확인 + 인덱스 번호랑 column이름 정확한지 확인, 자료형 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      float64
 2   KCAL    7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [237]:
## 자료형 변환하기 / astype / object -> int (형변환 확인)
df['PRICE'] = df['PRICE'].astype('int')
df.info()
## df['PRICE'] = df['PRICE'].astype('int')  ## 데이터['항목'].astype('자료형')
df['KCAL'] = df['KCAL'].astype('float')
df.info() ## KCAL 항목을 object 에서 float(실수형)으로 변환

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      int64
 2   KCAL    7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MENU    7 non-null      object
 1   PRICE   7 non-null      int64
 2   KCAL    7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [48]:
# 자료형 변환 / astype /  object -> int
df['가격'] = df['가격'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [49]:
df['칼로리'] = df['칼로리'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

## Section5. 새로운 컬럼 추가

In [50]:
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [240]:
## 컬럼 추가
df = pd.read_csv('cafe.csv')
df.head() ## .head() 함수의 경우 데이터를 5행 출력해서 보여줌

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [244]:
df['new'] = 0
df.head() ## 행 항목이 아닌 열 항목(세로축)으로 값이 0인 new 컬럼이 추가됨

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0
2   카페모카  5500  250    0
3   카푸치노  5000  110    0
4  에스프레소  4000   20    0

In [247]:
### 할인가 항목 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount) ## 1-0.2 = 0.8 (20% 할인가를 의미)
df.head()

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0

In [51]:
# 새로운 컬럼 추가 (값은 0)
df['new'] = 0
df.head(2)

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0

In [52]:
# 할인가 컬럼 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount)
df.head(2)

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0

## Section6. 데이터 삭제 (컬럼, 행)

In [53]:
df = pd.read_csv('cafe.csv')
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

In [257]:
df = pd.read_csv('cafe.csv')
df.head()

## 행 삭제
df.drop(1, axis=0, inplace=True) ## 인덱스 1번에 해당하는 행 삭제(0부터 시작)
df.head() ## .drop('번호', axis=0, inplace=True)

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210

### 행 삭제

In [54]:
# 행 삭제
df.drop(1, axis=0, inplace=True)
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110

In [258]:
## 컬럼 삭제 axis=0일 경우, 행(가로) 삭제 axis=1일 경우, 열(세로)삭제
df = df.drop('칼로리', axis=1)
df.head() ## .drop('열 이름', axis=1) 열 삭제

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000
4  에스프레소  4000
5    밀크티  5900

### 컬럼 삭제

In [55]:
# 데이터 삭제
# axis=0:행방향, axis=1:열방향(컬럼)
df = df.drop('칼로리', axis=1)
df.head(3)

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000

## Section7. 인덱싱/슬라이싱(loc)
- 인덱스 명
- 인덱스 명(범위), 컬럼 명(범위)

In [56]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [269]:
## 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head()

df.loc[0] ## 행 전체 가져오기  오 행, 열 헷갈리네

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [270]:
df.loc[1, '가격'] ## 카페라떼 loc[1]의 '가격' 항목 가져오기

np.int64(5000)

In [57]:
# 인덱싱 (행 전체)
# 아메리카노
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [58]:
# 카페라떼 가격
df.loc[1, "가격"]

np.int64(5000)

In [272]:
## 어렵네 이번거
df.loc[:, '가격'] ## 모든 행의 가격 항목만 전체 출력

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [59]:
# 슬라이싱 (컬럼 전체)
# 가격
df.loc[:, "가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [60]:
# 슬라이싱
df.loc[2, '메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [274]:
df.loc[2, '메뉴':'칼로리'] ## .loc[2] 카페모카의 '메뉴'부터 '칼로리'까지 (중간에 가격 포함)

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [61]:
# 슬라이싱
# 카페모카 메뉴와 칼로리
df.loc[2, ['메뉴', '칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [62]:
# 슬라이싱
df.loc[1:3, '메뉴':'가격']

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

In [276]:
df.loc[1:3, '메뉴':'가격'] ## 인덱스 1부터 3까지의 '메뉴' 부터 '가격' 항목까지 가져오기

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

## Section8. 인덱싱/슬라이싱(iloc)
- 인덱스 번호
- 인덱스 번호(범위), 컬럼 번호(범위)

In [281]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
#df.drop(0, axis=0, inplace=True) # 첫번째 행 삭제
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [285]:
## 기초만 하다가 시험보게 되는거 아녀
df = pd.read_csv('cafe.csv')
df.drop(0, axis=0, inplace=True) ## 0번으로 들어가는 행 삭제
df.head()

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210

In [286]:
# 인덱싱 (행 전체)
# 카페라떼
df.iloc[0]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [287]:
## 보여줘 카페라떼
df.iloc[0]  ## loc iloc 차이를 알아두기 (loc: 이름기반 / iloc: 순서기반)

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [289]:
df.iloc[:, 1] ## 모든 행의 가격(,iloc[1])을 출력

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [65]:
# 슬라이싱 (컬럼 전체)
# 가격
df.iloc[:, 1]

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [66]:
# 슬라이싱
# 카페모카 메뉴와 가격
df.iloc[2, 0:2]

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [291]:
df.iloc[2, 0:2] ## iloc[2] = 카푸치노 iloc[, 0:2] = 메뉴 부터 가격 까지

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [67]:
# 슬라이싱 (카페라떼와 카페모카의 전체 데이터)
df.iloc[1:3]

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [293]:
df.iloc[1:3] ## 모든 항목을 출력하는데, 인덱스 1부터 3까지 해당하는 행만 출력하는거

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [296]:
df.loc[2:3, '메뉴':'칼로리'] ## loc[2:3]은 카페모카-카푸치노에 해당하는거 / '메뉴', '칼로리' 항목 값 출력

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [68]:
df.loc[2:3,'메뉴':'칼로리']

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

## Section9. 데이터 추가/변경

In [69]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [301]:
## 데이터 다시 불러오기. 다.시. 불러오기.
df = pd.read_csv('cafe.csv')
df.head()

## 새로운 거 나오네
import numpy as np
df['원산지'] = np.nan ## 원산지 컬럼 만들고 일단 결측값으로 추가함 (np.nan = NaN) numpy가 제공하는 NaN 값임
df.head()

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN
4  에스프레소  4000   20  NaN

In [70]:
# 결측값으로 추가, 원두 컬럼을 만들고 결측값(NaN)으로 대입
import numpy as np
df['원산지'] = np.nan
df.head(4)

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN

In [302]:
# 아메리카노의 원두는 '콜롬비아' 데이터 추가
df.loc[0, "원산지"] = '콜롬비아'
df.loc[2:3, "원산지"] = '과테말라'
df.head(4)

/tmp/ipykernel_3806/1959328268.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "원산지"] = '콜롬비아'

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라

In [303]:
### 원산지 항목 추가 '콜롬비아'와 '과테말라' 산 원두를 추가할 것임
df.loc[0, "원산지"] = '콜롬비아' ## 우선 첫번째 행 인덱스가 0이니까 0번째 값으로 '콜롬비아' 추가함
df.loc[2:3, '원산지'] = '과테말라' ## 인덱스 개념 숙지를 위해 하나 건너뛰고 2번부터 3까지 '과테말라' 추가함
df.head()

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN

In [72]:
# 리스트 형태로 데이터(행) 추가
df.loc['시즌'] = ['크리스마스라떼', 6000, 300, '한국']
df.tail(3)

         메뉴    가격  칼로리  원산지
5       밀크티  5900  210  NaN
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국

In [314]:
## 시즌메뉴를 추가할 것임, 인덱스 넘버는 특별하게 '시즌'으로 하고, 메뉴명은 '크리스마스라떼'로 추가함
df.loc['시즌'] = ['크리스마스라떼', 6000, 300, '한국'] ## 모든 항목을 추가할 것임. 이름 부터 가격, 칼로리, 아까 추가한 원산지
df.tail()

         메뉴    가격  칼로리  원산지
4     에스프레소  4000   20  NaN
5       밀크티  5900  210  NaN
6        녹차  5300    0  NaN
7      딴짓커피  2000   20  NaN
시즌  크리스마스라떼  6000  300   한국

In [73]:
# 딕셔너리 형태로 데이터(행) 추가
df.loc[7] = {'메뉴':'딴짓커피', '가격':2000, '칼로리':20}
df.tail(3)

         메뉴    가격  칼로리  원산지
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국
7      딴짓커피  2000   20  NaN

In [308]:
## 직접적으로 항목명을 지정해서 추가하는 방식을 알아볼것임
df.loc[7] = {'메뉴':'딴짓커피', '가격':2000, '칼로리':20} ## 7째 행으로 key-value 값을 모두 기재하여 추가함
df.tail()  ## 빅분기 준비하다가 거북목 생기겠슴

         메뉴    가격  칼로리  원산지
4     에스프레소  4000   20  NaN
5       밀크티  5900  210  NaN
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국
7      딴짓커피  2000   20  NaN

In [312]:
## 시즌메뉴 끝나서 행 날릴거임
df.drop('시즌', axis=0, inplace=True) ## 시즌 '행' axis=0 을 날릴 것임
df.to_csv('cafe2.csv',index=False) ## 다음에도 사용할 거라 새 파일로 저장하는 단계임. 물론, 인덱스 번호는 제외하고

In [315]:
df.drop("시즌", axis=0, inplace=True)
df.to_csv('cafe2.csv', index=False)

## Section10. 정렬

In [75]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [317]:
## 정렬하기
df = pd.read_csv('cafe2.csv') ## 아까 새로 저장한 cafe2.csv 불러올 것임
df.head()
df.tail()

      메뉴    가격  칼로리   원산지
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [319]:
## 인덱스 기준 내림차순으로 정렬하자 ascending=False "내링차순 : 숫자가 내려가는 순서" - 기본값은 ascending=True
df.sort_index(ascending=False)

      메뉴    가격  칼로리   원산지
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN
5    밀크티  5900  210   NaN
4  에스프레소  4000   20   NaN
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
0  아메리카노  4500   10  콜롬비아

In [76]:
# 인덱스 기준 (기본값 ascending=True)
df.sort_index(ascending=False)

      메뉴    가격  칼로리   원산지
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN
5    밀크티  5900  210   NaN
4  에스프레소  4000   20   NaN
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
0  아메리카노  4500   10  콜롬비아

In [77]:
# 값 기준 (기본값 ascending=True)
# 메뉴 기준 정렬
df.sort_values('메뉴',ascending=False)

      메뉴    가격  칼로리   원산지
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
4  에스프레소  4000   20   NaN
0  아메리카노  4500   10  콜롬비아
5    밀크티  5900  210   NaN
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN

In [322]:
## 인데스 번호 말고 값 기준으로 정렬해보기
## 1. 메뉴 이름 기준으로 내림차순 정렬 (ㅎ->ㄱ 순으로 감)
df.sort_values('메뉴', ascending=False)

      메뉴    가격  칼로리   원산지
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
4  에스프레소  4000   20   NaN
0  아메리카노  4500   10  콜롬비아
5    밀크티  5900  210   NaN
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN

In [325]:
## 두 가지 조건 적용
## 가격과 메뉴를 기준으로 정렬 할 것임
df.sort_values(['가격','메뉴'], ascending=[False,True], inplace=True)  ## inplace=True 는 해당 조건으로 직접 변경을 의미함. 따로 저장할 필요가 없음
df  ## '가격'은 내림차, '메뉴'는 오름차...가 아닌데? 가격 내림차순

      메뉴    가격  칼로리   원산지
5    밀크티  5900  210   NaN
2   카페모카  5500  250  과테말라
6     녹차  5300    0   NaN
1   카페라떼  5000  110   NaN
3   카푸치노  5000  110  과테말라
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [78]:
# 가격과 메뉴 기준 정렬
df.sort_values(['가격', '메뉴'],ascending=[False, True], inplace=True)
df

      메뉴    가격  칼로리   원산지
5    밀크티  5900  210   NaN
2   카페모카  5500  250  과테말라
6     녹차  5300    0   NaN
1   카페라떼  5000  110   NaN
3   카푸치노  5000  110  과테말라
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [327]:
## 인덱스를 새로 생성함 drop=True (정렬 전 인덱스 버리기) .reset_index(drop=True) ## 인덱스 재정렬 하면서 기존 인덱스 버린다고 drop=True
df.reset_index(drop=True)

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [79]:
# 인덱스 새로 만들기 drop=True
df.reset_index(drop=True)

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

## Section11. 필터링

In [80]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [330]:
df = pd.read_csv('cafe2.csv')
df.head()  ## 해 뜰 시간이 다 됐네..

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN

In [331]:
## 조건에 해당하는지 boolean 값으로 확인
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [81]:
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [336]:
## 1개 조건으로 필터링
cond = df['칼로리'] < 50
df[cond]  ## 필터링 조건은 '' 으로 묶는거 아님 항목이 아니니까. 대충 칼로리가 50 미만인 값들만 필터링해서 보여줌

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [82]:
# 1개 조건
cond = df['칼로리'] < 50
df[cond]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [83]:
# 1개 조건
df[df['칼로리'] < 50]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [337]:
## 아예 직접적인 명시
df[df['칼로리'] < 50]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [340]:
cond = df['칼로리'] < 50 ## 칼로리가 50 미만인 조건을 줌
df[~cond]  ## 근데 나는 50 이상인 데이터가 필요해 ~ (NOT) 붙여주기

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [84]:
cond = df['칼로리'] < 50
df[~cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [342]:
# 2개 이상 일때 (AND)
cond1 = df['가격'] >= 5000
cond2 = df['칼로리'] > 100
df[cond1 & cond2]   ## 조건 1을 cond1로 걸음 / 조건 2를 cond2로 걸음 / 두 조건을 df[cond1 & cond2]로 묶어버림
## OR 도 같은 맥락에서 | 로 묶어버림

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [86]:
# 2개 이상 일때 (OR)
df[cond1 | cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN
6    녹차  5300    0   NaN

In [87]:
# 문자열 1개 조건
# 원두 == 콜롬비아
cond = (df['원산지'] == "과테말라")
df[cond]

     메뉴    가격  칼로리   원산지
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라

In [346]:
## 행 조건을 걸어버림
cond = (df['원산지'] == '과테말라')
df[cond] ## df에 끼워넣음

     메뉴    가격  칼로리   원산지
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라

In [88]:
# 문자열과 숫자 조건 (AND)
cond1 = df['원산지'] == "과테말라"
cond2 = df['가격'] <= 5000
df[cond1 & cond2]

     메뉴    가격  칼로리   원산지
3  카푸치노  5000  110  과테말라

In [89]:
df['메뉴'].isin(['녹차'])

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [349]:
## 조건에 맞는지 확인(boolean 값 확인)
df['메뉴'].isin(['녹차']) ## '메뉴' 이름에 '녹차' 값이 isin (존재하는지) 확인

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [90]:
cond = df['메뉴'].isin(['녹차'])
df[cond]

   메뉴    가격  칼로리  원산지
6  녹차  5300    0  NaN

In [352]:
box = ['녹차','카푸치노','카페라떼']
cond = df['메뉴'].isin(box)  ## isin() 은 함수니까 ()임. 안에는 항목
df[cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
3  카푸치노  5000  110  과테말라
6    녹차  5300    0   NaN

In [360]:
box = ['녹차', '카푸치노', '카페라떼']
cond = df['메뉴'].isin(box)
df[cond]

     메뉴    가격  칼로리
1  카페라떼  5000  110
3  카푸치노  5000  110
6    녹차  5300    0

## Section12. 결측치 처리

In [92]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [361]:
## 오 이거 중요함 1번 문제
df = pd.read_csv('cafe2.csv')
df.head()

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN

In [362]:
## 결측치가 있는지 확인
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [363]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [364]:
# 컬럼별 결측치 확인
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [365]:
## 컬럼별 결측치 확인하기
df.isnull().sum()  ## df.isnull() - 모든 컬럼, 행에 대하여 결측치 확인 / df.isnull().sum() - 합산해서 한 눈에 보기

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [95]:
# 컬럼별 결측치 확인
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [359]:
df.isna().sum() ## 원산지 어디감

메뉴     0
가격     0
칼로리    0
dtype: int64

In [366]:
df.isna().sum() ## NaN 값 확인 isna() <-> isnull()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [367]:
## 원산지 결측값을 '코스타리카'로 채우기
df['원산지'].fillna('코스타리카', inplace=True) ## 아까 drop하고 얘 결측치 .fillna() 에 inplace=True 확인할 것
df

/tmp/ipykernel_3806/3518602803.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카', inplace=True) ## 아까 drop하고 얘 결측치 .fillna() 에 inplace=True 확인할 것

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [96]:
# 결측값 채우기 (FutureWarning은 무시해도 된다.)
df['원산지'].fillna('코스타리카', inplace=True)
df

/tmp/ipykernel_3806/322007724.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카', inplace=True)

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [97]:
df.to_csv("cafe3.csv", index=False)

In [369]:
## 원산지 값이 모두 추가된 cafe.csv를 cafe3.csv로 저장
df.to_csv('cafe3.csv', index=False) ## index는 저장하지 말 것 옵션: index=False

## Section13. 값 변경

In [98]:
# 데이터 확인
pd.read_csv("cafe3.csv")
df.head(3)

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라

In [372]:
## 데이터 확인하기
pd.read_csv('cafe3.csv')
df.head()

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카

In [376]:
## 기존 데이터에 있는 값을 변경할 것임 (replace를 옵션값이 아닌 함수로 적용)
df.replace('아메리카노', '룽고', inplace=True)
df.replace('녹차','그린티', inplace=True)
df ## 룽고 보단 아메리카노가 좋은데

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [99]:
# 문자 변경 : 아메리카노 -> 룽고, 녹차 -> 그린티
df.replace('아메리카노', '룽고', inplace=True)
df.replace('녹차','그린티', inplace=True)
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [100]:
change = {'룽고':'아메리카노', '그린티':'녹차'}
df.replace(change, inplace=True)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [378]:
## 조건을 넣어주는 방법을 사용할 수도 있음
change = {'룽고':'아메리카노', '그린티':'녹차'}
df.replace(change, inplace=True)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [380]:
### 아예 직접 명시하는 방법도 있음
df.loc[6, '원산지'] = '대한민국'  ## 국내산으로 변경 6번째 인덱스 메뉴
df.tail()

      메뉴    가격  칼로리    원산지
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0   대한민국
7   딴짓커피  2000   20  코스타리카

In [101]:
# loc로 값 변경하기
df.loc[6, '원산지'] = '대한민국'
df.tail(3)

     메뉴    가격  칼로리    원산지
5   밀크티  5900  210  코스타리카
6    녹차  5300    0   대한민국
7  딴짓커피  2000   20  코스타리카

In [102]:
# 이벤트가 전체 1000으로 변경
df.loc[1:2, '이벤트가'] = 1000
df.head()

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN

In [381]:
## 이벤트가 컬럼을 새로 추가하고 인덱스 1, 2 항목에만 1000으로 추가
df.loc[1:2, '이벤트가'] = 1000
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓커피  2000   20  코스타리카     NaN

In [382]:
## 작업물 저장
df.to_csv('cafe4.csv', index=False)

In [103]:
df.to_csv("cafe4.csv", index=False)

In [104]:
# map() 함수
import pandas as pd
df = pd.DataFrame({'만족도': ['만족', '보통' ,'불만', '보통', '만족']})

mapping = {'만족': 3, '보통': 2, '불만': 1}
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3

In [387]:
## 오 파이썬 할 때 map 하기 싫었는데
import pandas as pd
df = pd.DataFrame({'만족도': ['만족', '보통', '불만', '보통','만족']}) ## '만족도' 에 대한 값이 리스트 형식임
mapping = {'만족': 3, '보통' : 2, '불만' : 1}  #### key - value 기반으로 매핑됨
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3

## Section14. 문자열

In [105]:
import pandas as pd
df = pd.DataFrame({'A': ['데이터 분석', '기본 학습서', '퇴근 후 열공'],
                   'B': [10, 20, 30],
                   'C': ['ab cd', 'AB CD', 'ab cd ']
                   })
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [390]:
import pandas as pd
### 문자열 학습하기
df = pd.DataFrame({
    'A': ['데이터 분석','기본 학습서','퇴근 후 열공'], ## 현실에서의 '퇴근 후 열공'은 무척 어렵습니다. 진짜로.
    'B': [10, 20, 30],
    'C' : ['ab cd', 'AB CD' ,'ab cd ']
})
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [106]:
df['A'] = df['A'].replace('분석', '시각화')
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [392]:
## 'A'는 성의없으니께 다른 단어로 치환해볼게요
df['A'] = df['A'].replace('분석','시각화')
df  ## 오 왜 변한게 없을까요

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [107]:
df['A'] = df['A'].str.replace('분석', '시각화')
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [395]:
df['A'] = df['A'].str.replace('분석','시각화') ## 문자열 치환에는 df[]에 .str 로 문자열 임을 명시를 꼭 해줘야 함
df ## 변경 확인

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [108]:
df['B'] = df['B'].replace(10, 100)
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [397]:
## 그럼 숫자 데이터는 치환 시 str 여부가 어떻게 되는지
df['B'] = df['B'].replace(10, 100)
df ## 역시 str 없이 잘 치환되는 것을 확인할 수 있쥬

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [109]:
# 에러
# df['B'] = df['B'].str.replace(20, 200)
# print(df)

In [110]:
# 문자열 분리
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [399]:
## 문자열 분리하는 법에 대하여 알아보아요
df['A'].str.split()  ## .split() 에 아무런 기호, 값을 주지 않으면 띄어쓰기(공백) 기준으로 문자열을 분리해버려유

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [406]:
df['A'].str.split()[0] ## 첫 번째 행에 대해서만 분리를 시도해봐유
df['D'] = df['A'].str.split().str[0] ## 이름 'A'에 해당하는 항목의 첫번째 문자열 str[0]만 따서 'D'로 추가해줄게유 (데이터 항목에도 .str 필수)
df  ## 참 쉽쥬

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [111]:
df['A'].str.split()[0]

['데이터', '시각화']

In [112]:
df['D'] = df['A'].str.split().str[0]
df

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [113]:
# 문자 검색
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [408]:
## 특정 문자열을 포함하고 있는 데이터가 있는지 확인해유
df['A'].str.contains('기본') ## 문자열이니까 .str 추가하고 contains() 는 함수라서 ()로 묶음

0    False
1     True
2    False
Name: A, dtype: bool

In [409]:
## 확인하기 위해 새로운 컬럼으로 추가
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B       C    D  기본포함유무
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [114]:
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B       C    D  기본포함유무
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [115]:
menu = pd.Series(['맛난버거 세트', '매운 치킨버거', '더블 치즈버거'])
menu.isin(['맛난버거 세트', '더블 치즈버거'])

0     True
1    False
2     True
dtype: bool

In [412]:
menu = pd.Series(['맛난버거 세트', '매운 치킨버거' ,'더블 치즈버거'])
menu.isin(['맛난버거 세트','더블 치즈버거'])  ## 특정 문자열이 데이터에 존재하는지 확인

0     True
1    False
2     True
dtype: bool

In [413]:
## '세트' 메뉴가 있는지 확인
menu.str.contains('세트') ## contains() 쓰려면 str은 거의 필수

0     True
1    False
2    False
dtype: bool

In [116]:
menu.str.contains('세트')

0     True
1    False
2    False
dtype: bool

In [414]:
df['문자길이'] = df['A'].str.len()
df
## 문자길이 .str.len()
## 대문자 변환 .str.upper()
## 소문자 변환 .str.lower()

         A    B       C    D  기본포함유무  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [118]:
'AB cd' == 'ab CD'

False

In [119]:
df['C'] = df['C'].str.lower()
df['C']

0     ab cd
1     ab cd
2    ab cd
Name: C, dtype: object

In [120]:
df['C'] = df['C'].str.upper()
df['C']

0     AB CD
1     AB CD
2    AB CD
Name: C, dtype: object

In [121]:
df['C'] == 'AB CD'

0     True
1     True
2    False
Name: C, dtype: bool

In [416]:
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(" ","")  ## 공백 제거
df['C']

0    abcd
1    abcd
2    abcd
Name: C, dtype: object

In [418]:
df['C'].str[1:3]  ## C 항목의 두번째 값(인덱스 1)부터 세번째 값(인덱스 2)까지

0    bc
1    bc
2    bc
Name: C, dtype: object

In [124]:
df['C'][1:3]

1    abcd
2    abcd
Name: C, dtype: object

In [ ]:
#### 우선 여기까지. 빅분기 실기 합격률 평균 적으면 40대~ 최대 60까지 나옴 ** 근데 난 빅분기가 싫어요

## Section15. 내장함수
- 데이터 핸들링을 위한 판다스 기초1(EDA) 부분에서 일부 내장함수를 학습했고, 그외 함수에 대해 살펴봄

In [125]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [126]:
print(len(df))
print(df.shape[0])

8
8

In [127]:
cond = df['가격'] > 5000

#sum으로 조건에 맞는 개수 구하기
print(sum(cond))

#len으로 조건에 맞는 개수 구하기
print(len(df[cond]))

3
3

In [128]:
df.sum(numeric_only=True)

가격      37200.0
칼로리       730.0
이벤트가     2000.0
dtype: float64

In [129]:
df.sum(axis=1, numeric_only=True)

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    2020.0
dtype: float64

In [130]:
print("최대값: ",df['가격'].max())
print("최소값: ",df['가격'].min())
print("평균값: ",df['가격'].mean())
print("중앙값: ",df['가격'].median())
print("합계: ",df['가격'].sum())
print("표준편차: ",df['가격'].std())
print("분산: ",df['가격'].var())

최대값:  5900
최소값:  2000
평균값:  4650.0
중앙값:  5000.0
합계:  37200
표준편차:  1220.070255588353
분산:  1488571.4285714286

In [131]:
# 분위수
print("분위수 25% 값", df['가격'].quantile(.25))
print("분위수 75% 값", df['가격'].quantile(.75))

분위수 25% 값 4375.0
분위수 75% 값 5350.0

In [132]:
# 하위 25% 데이터
cond = df['가격'].quantile(.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
4  에스프레소  4000   20  코스타리카   NaN
7   딴짓커피  2000   20  코스타리카   NaN

In [133]:
# 상위 25% 데이터
cond = df['가격'].quantile(.75) < df['가격']
df[cond]

     메뉴    가격  칼로리    원산지    이벤트가
2  카페모카  5500  250   과테말라  1000.0
5   밀크티  5900  210  코스타리카     NaN

In [134]:
# 최빈값 구하기
df['원산지'].mode()[0]

'코스타리카'

In [135]:
df['가격'].idxmax()

5

In [136]:
max_ind = df['가격'].idxmax()
df.loc[max_ind]

메뉴        밀크티
가격       5900
칼로리       210
원산지     코스타리카
이벤트가      NaN
Name: 5, dtype: object

In [137]:
# df.loc[max_ind, '메뉴'] # 추천 방법
df.loc[max_ind]['메뉴'] # 다른 방법

'밀크티'

In [138]:
df.nlargest(3, '가격')

     메뉴    가격  칼로리    원산지    이벤트가
5   밀크티  5900  210  코스타리카     NaN
2  카페모카  5500  250   과테말라  1000.0
6    녹차  5300    0   대한민국     NaN

In [139]:
df.nsmallest(2, '가격')

      메뉴    가격  칼로리    원산지  이벤트가
7   딴짓커피  2000   20  코스타리카   NaN
4  에스프레소  4000   20  코스타리카   NaN

In [140]:
# apply 적용해서 새로운 컬럼 생성 (칼로리 컬럼 활용)
def cal(x):
    if x >= 100:
        return "No"
    else:
        return "Yes"

df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

      메뉴    가격  칼로리    원산지    이벤트가 먹어도 될까요
0  아메리카노  4500   10   콜롬비아     NaN     Yes
1   카페라떼  5000  110  코스타리카  1000.0      No
2   카페모카  5500  250   과테말라  1000.0      No
3   카푸치노  5000  110   과테말라     NaN      No
4  에스프레소  4000   20  코스타리카     NaN     Yes
5    밀크티  5900  210  코스타리카     NaN      No
6     녹차  5300    0   대한민국     NaN     Yes
7   딴짓커피  2000   20  코스타리카     NaN     Yes

In [141]:
import pandas as pd
df = pd.DataFrame({'Name': {0: '쿼카', 1: '알파카', 2: '시바견'},
                   '수학': {0: 90, 1: 93, 2: 85},
                   '영어': {0: 92, 1: 84, 2: 86},
                   '국어': {0: 91, 1: 94, 2: 83},})

df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [142]:
pd.melt(df, id_vars=['Name'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [143]:
pd.melt(df, id_vars=['Name'], value_vars=['수학', '영어'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86

In [144]:
pd.melt(df, id_vars=['Name'], var_name='과목', value_name='점수')

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86
6   쿼카  국어  91
7  알파카  국어  94
8  시바견  국어  83

In [145]:
import pandas as pd

df = pd.DataFrame({
    "반": ["A반", "A반", "B반"],  # 반 정보 추가
    "이름": ["쿼카", "알파카", "시바견"],
    "수학": [90, 93, 85],
    "영어": [92, 84, 86],
    "국어": [91, 94, 83]
})
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  86  83

In [146]:
pd.melt(df, id_vars=["반", "이름"], var_name="과목", value_name="점수")

    반   이름  과목  점수
0  A반   쿼카  수학  90
1  A반  알파카  수학  93
2  B반  시바견  수학  85
3  A반   쿼카  영어  92
4  A반  알파카  영어  84
5  B반  시바견  영어  86
6  A반   쿼카  국어  91
7  A반  알파카  국어  94
8  B반  시바견  국어  83

## Section16. 그룹핑

In [147]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [148]:
# 원두 기준, 평균
df.groupby(['원산지']).mean(numeric_only=True)

           가격    칼로리    이벤트가
원산지
과테말라   5250.0  180.0  1000.0
대한민국   5300.0    0.0     NaN
코스타리카  4225.0   90.0  1000.0
콜롬비아   4500.0   10.0     NaN

In [149]:
# 원두와 할인율 기준, 평균
df.groupby(['원산지', '칼로리']).mean(numeric_only=True)

               가격    이벤트가
원산지   칼로리
과테말라  110  5000.0     NaN
      250  5500.0  1000.0
대한민국  0    5300.0     NaN
코스타리카 20   3000.0     NaN
      110  5000.0  1000.0
      210  5900.0     NaN
콜롬비아  10   4500.0     NaN

In [150]:
df.groupby(['원산지', '메뉴']).agg(['mean', 'sum'])

                 가격          칼로리         이벤트가
               mean   sum   mean  sum    mean     sum
원산지   메뉴
과테말라  카페모카   5500.0  5500  250.0  250  1000.0  1000.0
      카푸치노   5000.0  5000  110.0  110     NaN     0.0
대한민국  녹차     5300.0  5300    0.0    0     NaN     0.0
코스타리카 딴짓커피   2000.0  2000   20.0   20     NaN     0.0
      밀크티    5900.0  5900  210.0  210     NaN     0.0
      에스프레소  4000.0  4000   20.0   20     NaN     0.0
      카페라떼   5000.0  5000  110.0  110  1000.0  1000.0
콜롬비아  아메리카노  4500.0  4500   10.0   10     NaN     0.0

In [151]:
# 1개 인덱스 형태로 리셋
df.groupby(['원산지', '칼로리']).mean(numeric_only=True).reset_index()

     원산지  칼로리      가격    이벤트가
0   과테말라  110  5000.0     NaN
1   과테말라  250  5500.0  1000.0
2   대한민국    0  5300.0     NaN
3  코스타리카   20  3000.0     NaN
4  코스타리카  110  5000.0  1000.0
5  코스타리카  210  5900.0     NaN
6   콜롬비아   10  4500.0     NaN

In [152]:
# transform
import pandas as pd

# 데이터 생성 (일부 결측값 포함)
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [153]:
price = df.groupby('과일')['가격'].transform("mean")
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [154]:
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [155]:
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '등급': ['B', 'B', 'A', 'A', 'A', 'A', 'B', 'B'],  # 새로운 그룹 추가
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [156]:
price = df.groupby(['과일', '등급'])['가격'].transform("mean")
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [157]:
df['가격'] = df['가격'].fillna(price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [158]:
# unstack
import pandas as pd

coffee_data = {
    '커피종류': ['아메리카노', '아메리카노', '아메리카노', '라떼', '라떼', '라떼'],
    '컵크기': ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Large'],
    '판매량': [120, 150, 200, 100, 130, 180]
}
df = pd.DataFrame(coffee_data)
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [159]:
# groupby 적용
grouped = df.groupby(['커피종류', '컵크기'])['판매량'].sum()
grouped

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [160]:
# 컵크기를 컬럼으로 변환
grouped.unstack()

컵크기    Large  Medium  Small
커피종류
라떼       180     130    100
아메리카노    200     150    120

In [161]:
# 커피종류를 컬럼으로 변환
grouped.unstack(level=0)

커피종류     라떼  아메리카노
컵크기
Large   180    200
Medium  130    150
Small   100    120

In [162]:
# 두 번의 unstack 적용
grouped.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

## Section17. 시계열 데이터 (Datetime)

In [163]:
import pandas as pd
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
    'DateTime1': ['24-02-17 13:45:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
    'DateTime2': ['2024-02-17 13-45-30', '2024-02-18 14-55-45', '2024-02-19 15-30-15', '2024-02-20 16-10-50'],
    'DateTime3': ['02/17/2024 01:45:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
    'DateTime4': ['17 Feb 2024 13:45:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50']
}

df = pd.DataFrame(data)
df.to_csv("date_data.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:45:30,2024-02-17 13-45-30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14-55-45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15-30-15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16-10-50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [165]:
df = pd.read_csv("date_data.csv")
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'])
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
df

/tmp/ipykernel_3806/2722885956.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])
/tmp/ipykernel_3806/2722885956.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime1'] = pd.to_datetime(df['DateTime1'])
/tmp/ipykernel_3806/2722885956.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime3'] = pd.to_datetime(df['DateTime3'])

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2017-02-24 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2018-02-24 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2019-02-24 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2020-02-24 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50

In [166]:
df = pd.read_csv("date_data.csv")
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'], format='%y/%m/%d')
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format='%y-%m-%d %H:%M:%S')
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df[['Date2', 'Date3', 'DateTime1', 'DateTime2']]

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [167]:
cols = ['Date2', 'Date3', 'DateTime1', 'DateTime2']
df[cols]

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: datetime64[ns](4), object(5)
memory usage: 420.0+ bytes

In [169]:
df['year'] = df['DateTime1'].dt.year
df['month'] = df['DateTime1'].dt.month
df['day'] = df['DateTime1'].dt.day
df['hour'] = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,second
0,2024-02-17,2024-02-17,2024-02-17,02/17/2024,17-Feb-2024,2024-02-17 13:45:30,2024-02-17 13:45:30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30,2024,2,17,13,45,30
1,2024-02-18,2024-02-18,2024-02-18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18 14:55:45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45,2024,2,18,14,55,45
2,2024-02-19,2024-02-19,2024-02-19,02/19/2024,19-Feb-2024,2024-02-19 15:30:15,2024-02-19 15:30:15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15,2024,2,19,15,30,15
3,2024-02-20,2024-02-20,2024-02-20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20 16:10:50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50,2024,2,20,16,10,50

In [170]:
df['DateTime1'].dt.dayofweek

0    5
1    6
2    0
3    1
Name: DateTime1, dtype: int32

In [171]:
print(df['DateTime1'].dt.to_period('Y'))
print(df['DateTime1'].dt.to_period('Q'))
print(df['DateTime1'].dt.to_period('M'))
print(df['DateTime1'].dt.to_period('D'))
print(df['DateTime1'].dt.to_period('H'))

0    2024
1    2024
2    2024
3    2024
Name: DateTime1, dtype: period[Y-DEC]
0    2024Q1
1    2024Q1
2    2024Q1
3    2024Q1
Name: DateTime1, dtype: period[Q-DEC]
0    2024-02
1    2024-02
2    2024-02
3    2024-02
Name: DateTime1, dtype: period[M]
0    2024-02-17
1    2024-02-18
2    2024-02-19
3    2024-02-20
Name: DateTime1, dtype: period[D]
0    2024-02-17 13:00
1    2024-02-18 14:00
2    2024-02-19 15:00
3    2024-02-20 16:00
Name: DateTime1, dtype: period[h]

/tmp/ipykernel_3806/2095775091.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  print(df['DateTime1'].dt.to_period('H'))

## Section18. 시계열 데이터 (Timedelta)

In [172]:
df = pd.read_csv("date_data.csv", usecols=['DateTime4'], parse_dates=['DateTime4'])
df

            DateTime4
0 2024-02-17 13:45:30
1 2024-02-18 14:55:45
2 2024-02-19 15:30:15
3 2024-02-20 16:10:50

In [173]:
day = pd.Timedelta(days=99)
df['100day'] = df['DateTime4'] + day
df

            DateTime4              100day
0 2024-02-17 13:45:30 2024-05-26 13:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50

In [174]:
hour = pd.Timedelta(hours=100)
df['100hour'] = df['DateTime4'] + hour
df

            DateTime4              100day             100hour
0 2024-02-17 13:45:30 2024-05-26 13:45:30 2024-02-21 17:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45 2024-02-22 18:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15 2024-02-23 19:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50 2024-02-24 20:10:50

In [175]:
difference = pd.Timedelta(weeks=7, days=7, hours=7, minutes=7, seconds=7)
df['difference'] = df['DateTime4'] - difference
df

,DateTime4,100day,100hour,difference
0,2024-02-17 13:45:30,2024-05-26 13:45:30,2024-02-21 17:45:30,2023-12-23 06:38:23
1,2024-02-18 14:55:45,2024-05-27 14:55:45,2024-02-22 18:55:45,2023-12-24 07:48:38
2,2024-02-19 15:30:15,2024-05-28 15:30:15,2024-02-23 19:30:15,2023-12-25 08:23:08
3,2024-02-20 16:10:50,2024-05-29 16:10:50,2024-02-24 20:10:50,2023-12-26 09:03:43

In [176]:
diff = df['100hour'] - df['difference']
diff

0   60 days 11:07:07
1   60 days 11:07:07
2   60 days 11:07:07
3   60 days 11:07:07
dtype: timedelta64[ns]

In [177]:
print(diff.dt.total_seconds()) # 초
print(diff.dt.total_seconds()/60) # 분
print(diff.dt.total_seconds()/60/60) # 시간
print(diff.dt.total_seconds()/60/60/24) # 일

0    5224027.0
1    5224027.0
2    5224027.0
3    5224027.0
dtype: float64
0    87067.116667
1    87067.116667
2    87067.116667
3    87067.116667
dtype: float64
0    1451.118611
1    1451.118611
2    1451.118611
3    1451.118611
dtype: float64
0    60.463275
1    60.463275
2    60.463275
3    60.463275
dtype: float64

In [178]:
print(diff.dt.days)
print(diff.dt.seconds)

0    60
1    60
2    60
3    60
dtype: int64
0    40027
1    40027
2    40027
3    40027
dtype: int32

In [179]:
min = 5.41
print(int(min), "분")
print(0.41*60, "초")

5 분
24.599999999999998 초

In [180]:
print(round(diff.dt.total_seconds()/60))

0    87067.0
1    87067.0
2    87067.0
3    87067.0
dtype: float64

## Section19. 데이터 합치기

In [181]:
import pandas as pd

# 에피타이저 메뉴
appetizer = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Bread'],
    'Price': [5000, 3000, 2000]
})

# 메인 메뉴
main = pd.DataFrame({
    'Menu': ['Steak', 'Pasta', 'Chicken'],
    'Price': [15000, 12000, 10000]
})
print(appetizer)
print(main)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000
      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [182]:
# 두 메뉴를 수직으로 연결
full_menu = pd.concat([appetizer, main], ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [183]:
# 두 메뉴를 좌우로 연결
full_menu = pd.concat([appetizer, main], axis=1)
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [184]:
# 메뉴와 가격
price = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Steak', 'Pasta'],
    'Price': [5000, 3000, 15000, 12000]
})

# 메뉴와 칼로리
cal = pd.DataFrame({
    'Menu': ['Soup', 'Steak', 'Pasta','Salad'],
    'Calories': [100, 500, 400, 150]
})

# 두 데이터프레임을 'Menu'를 기준으로 병합
menu_info = pd.merge(price, cal, on='Menu')
menu_info

    Menu  Price  Calories
0  Salad   5000       150
1   Soup   3000       100
2  Steak  15000       500
3  Pasta  12000       400

## Section20.피벗테이블

In [185]:
import pandas as pd

# 직원별 부서 및 급여 정보
data = {
    '이름': ['서아', '다인', '채아', '예담', '종현', '태헌'],
    '부서': ['개발', '기획', '개발', '기획', '개발', '기획'],
    '급여': [3000, 3200, 3100, 3300, 2900, 3100]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서별 평균 급여 계산
pt = df.pivot_table(index='부서', values='급여', aggfunc='mean')
print("\n[부서별 평균 급여]") #\n은 줄 바꿈(새로운 줄 시작)
print(pt)

[원본 데이터]
   이름  부서    급여
0  서아  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

[부서별 평균 급여]
        급여
부서
개발  3000.0
기획  3200.0

In [186]:
# 부서와 직급별 급여 정보
data = {
    '부서': ['개발', '기획', '기획', '기획', '개발', '개발'],
    '직급': ['대리', '과장', '대리', '과장', '대리', '과장'],
    '급여': [3000, 4000, 3200, 4200, 3500, 4500]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 직급별 급여 합계 계산
pt = df.pivot_table(index='부서', columns='직급', values='급여', aggfunc='sum')
print("\n[부서 및 직급별 급여 합계]")
print(pt)

[원본 데이터]
   부서  직급    급여
0  개발  대리  3000
1  기획  과장  4000
2  기획  대리  3200
3  기획  과장  4200
4  개발  대리  3500
5  개발  과장  4500

[부서 및 직급별 급여 합계]
직급    과장    대리
부서
개발  4500  6500
기획  8200  3200

In [187]:
# 부서와 성별, 근속연수 정보
data = {
    '부서': ['개발', '기획', '기획', '기획', '개발', '개발'],
    '성별': ['남', '여', '남', '여', '남', '여'],
    '근속연수': [3, 5, 4, 6, 7, 8]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 성별 평균 근속연수 계산
pt = df.pivot_table(index='부서', columns='성별', values='근속연수', aggfunc='mean')
print("\n[부서 및 성별 평균 근속연수]")
print(pt)

[원본 데이터]
   부서 성별  근속연수
0  개발  남     3
1  기획  여     5
2  기획  남     4
3  기획  여     6
4  개발  남     7
5  개발  여     8

[부서 및 성별 평균 근속연수]
성별    남    여
부서
개발  5.0  8.0
기획  4.0  5.5

In [188]:
# 다양한 집계를 위한 데이터셋
import pandas as pd

df = pd.DataFrame({
    "구분": ["전자", "전자", "전자", "전자", "전자", "가전", "가전", "가전", "가전"],
    "유형": ["일반", "일반", "일반", "특수", "특수", "일반", "일반", "특수", "특수"],
    "크기": ["소형", "대형", "대형", "소형", "소형", "대형", "소형", "소형", "대형"],
    "수량": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    "금액": [2, 4, 5, 5, 6, 6, 8, 9, 9]
})
print(df)

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [189]:
# 단일 값에 대해 집계
pt = pd.pivot_table(
    df,
    values='수량',
    index=['구분', '유형'],
    columns=['크기'],
    aggfunc="sum"
)
pt

크기      대형   소형
구분 유형
가전 일반  4.0  5.0
   특수  7.0  6.0
전자 일반  4.0  1.0
   특수  NaN  6.0

In [190]:
# 단일 값에 대해 집계 (누락 값 0 처리)
pt = pd.pivot_table(
    df,
    values='수량',
    index=['구분', '유형'],
    columns=['크기'],
    aggfunc="sum",
    fill_value=0
)
pt

크기     대형  소형
구분 유형
가전 일반   4   5
   특수   7   6
전자 일반   4   1
   특수   0   6

In [191]:
# 여러 열에 대해 각기 다른 집계 함수 적용
pt = pd.pivot_table(
    df,
    values=['수량', '금액'],
    index=['구분', '크기'],
    aggfunc={'수량': "mean", '금액': "mean"}
)
pt

             금액        수량
구분 크기
가전 대형  7.500000  5.500000
   소형  8.500000  5.500000
전자 대형  4.500000  2.000000
   소형  4.333333  2.333333

In [192]:
# 하나의 열에 대해 여러 집계 함수를 동시에 적용
pt = pd.pivot_table(
    df,
    values=['수량', '금액'],
    index=['구분', '크기'],
    aggfunc={'수량': "mean", '금액': ["min", "max", "mean"]}
)
pt

       금액                      수량
      max      mean min      mean
구분 크기
가전 대형   9  7.500000   6  5.500000
   소형   9  8.500000   8  5.500000
전자 대형   5  4.500000   4  2.000000
   소형   6  4.333333   2  2.333333

In [193]:
pt.reset_index()

   구분  크기  금액                      수량
          max      mean min      mean
0  가전  대형   9  7.500000   6  5.500000
1  가전  소형   9  8.500000   8  5.500000
2  전자  대형   5  4.500000   4  2.000000
3  전자  소형   6  4.333333   2  2.333333

## Section21.Quiz

In [194]:
# 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '에스프레소', '카페모카', '바닐라라떼'],
    "가격":[4500, 5000, 4000, 5900, 5300],
    "칼로리":[10, 110, np.NaN, 210, np.NaN],
    "원산지":['과테말라','브라질','과테말라', np.NaN, np.NaN]
})
df

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

**1. '칼로리' 컬럼 결측치는 칼로리 데이터 중 최소값으로 결측치를 채우시오**

In [ ]:
min_cal = df['칼로리'].min()
df['칼로리'] = df['칼로리'].fillna(min_cal)
df

**2. '원산지' 컬럼 결측치는 원두 데이터 중 최빈값으로 결측치를 채우시오**

In [ ]:
f = df['원산지'].mode()[0]
df['원산지'] = df['원산지'].fillna(f)
df

**3. 가격이 5000 이상인 데이터의 수를 구하시오**

In [ ]:
cond = df['가격'] >= 5000
len(df[cond]) # 또는 sum(cond)

**4. ’이벤트가’ 컬럼을 만들고 기존 가격에서 50% 할인된 가격을 채우시오**

In [ ]:
df['이벤트가'] = df['가격'] * 0.5
df

**5. '칼로리' 컬럼을 삭제하시오**
-

In [ ]:
df = df.drop('칼로리', axis=1)
df

**6. 앞에서부터 3개의 데이터만 선택하시오(loc 활용)**

In [ ]:
df.loc[:2]

**7. 앞에서부터 3개의 데이터만 선택하시오(iloc 활용)**

In [ ]:
df.iloc[:3]

**8. 주어진 데이터(df)에서 아래 값을 loc를 활용해 데이터 프레임으로 출력하시오**
- 카페라떼	5000
- 에스프레소 4000

In [ ]:
# loc
df.loc[1:2, :'가격']

**9. 주어진 데이터(df)에서 아래 값을 iloc를 활용해 데이터 프레임으로 출력하시오**
- 카페라떼	5000
- 에스프레소 4000

In [ ]:
# iloc
df.iloc[1:3, :2]

**10. 메뉴 중 가격이 가장 비싼 순으로 정렬해 상위 3개 값을 구하시오**

In [ ]:
df = df.sort_values('가격', ascending=False)
df.iloc[:3]