<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/ch3_chi_square.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part3/ch3/ch3_chi_square.ipynb)

#1. 적합도 검정

In [8]:
## 카이제곱 적합도 검정 : 1개의 범주형 변수가 특정 분포를 잘 따르는지 검정
# 귀무가설 : 분포를 잘 따름 / 대립가설 : 분포를 따르지 않음
# 사용 라이브러리 scipy.stats.chisquare() "chi[싸이-]square[스퀘어r]"

## 문제 조건 : 300 명 대상으로 아이스크림 맛 선호도 조사
# 바닐라 150 초코 120 딸기 30 / 전국 평균 바닐라 50% 초코 35% 딸기 15%
# 귀무 : 이 도시의 아이스크림 맛 선호도는 전국과 동일 / 대립 : 이 도시의 선호도는 전국과 다름

# 1. 라이브러리 불러오기
##  문제에서 도시 = 빈도 / 전국 = 비율로 제시 -> 두 데이터를 통일시켜야 함 (빈도로 통일)
from scipy import stats

observed = [150, 120, 30] # 특정 도시에서 관측된 선호 수
expected = [0.5*300, 0.35*300, 0.15*300] # 비율로 제시된 전국 선호도를 "비율*인구수" 연산으로 데이터 통일

t_statistic, p_value = stats.chisquare(observed, expected)
print("기초통계량 : ", t_statistic) # 결과 :7.142857142857142
print("p-value : ", p_value) # 결과 : 0.028115659748972056

# p-value(0.02811) < 0.05 이므로 대립 채택 "이 도시의 아이스크림 맛 선호도는 전국적인 선호도와 동일하다"

## ** 사용함수 stats.chisquare(observed, expected, ddof , axis) ## ddof = 자유도 (기본=0) / axis=1 또는 axis=0
## 카이제곱 적합도 검정 시 기대 값은 빈도로 통일해서 입력할 것 (비율로 통일 시 결과 변동)

기초통계량 :  7.142857142857142
p-value :  0.028115659748972056

In [ ]:
from scipy import stats

observed = [150, 120, 30]
expected = [0.5*300, 0.35*300, 0.15*300]
print(stats.chisquare(observed, expected))

Power_divergenceResult(statistic=7.142857142857142, pvalue=0.028115659748972056)

# 2. 독립성 검정

## 2-1 교차표 데이터

In [23]:
## 카이제곱 독립성 검정 : 두 개의 변수가 독립적인지 연관이 있는지 검정
## 귀무 : 두 범주형 변수가 독립적 / 대립 : 두 범주형 변수가 연관
## scipy.stats.chi2_contigency() [chi2_contingency:싸이2-콘티n젼시]

## 문제 조건 : 성별에 따라 운동을 좋아하는지 조사한 결과. 성별과 운동 선호도가 독립적인지 가설검정 수행
# 귀무 : 성별과 운동 선호도는 독립 / 대립 : 성별과 운동 선호도는 독립적이지 않음(연관)
# 1. 교차표 데이터      2. 로우 데이터    - 주어진 데이터 유형에 따라 다른 풀이

## 0. 교차표 데이터
# 남자 : 좋아함 80명 / 좋아하지 않음 30명
# 여자 : 좋아함 90명 / 좋아하지 않음 10명

## 1. 라이브러리 및 데이터 프레임 생성(교차표 데이터 기반)
import pandas as pd

df = pd.DataFrame({
    '좋아함' : [80,90], ## 성별-선호도 잘 구분해서 입력하기
    '좋아하지 않음' : [30,10]
})
print(df) ## 교차표 데이터 확인

## 2. 독립성 검정 (성별에 따른 운동 선호도의 독립,연관성 조사)
# scipy.stats.chi2_contigency() 사용
from scipy import stats
print(stats.chi2_contingency(df))
# 결과 : statistic=np.float64(9.045792112299468), pvalue=np.float64(0.0026330012530379632), dof=1, expected_freq=array([[89.04761905, 20.95238095], [80.95238095, 19.04761905]]))
# 결과값 해석 : expected_freq=array([[89.04761905, 20.95238095], [80.95238095, 19.04761905]])) 이거 보는거임 - 근데 이 부분은 시험에서 제공 안 됨
# 89.0476 : 남자가 좋아함을 선택할 기대치 / 20.9523 : 남자가 좋아하지 않음을 선택할 기대치
# 80.9523 : 여자가 좋아함을 선택할 기대치 / 19.0476 : 여자가 좋아하지 않음을 선택할 기대치

# p-value(0.0026) < 0.05 이므로 대립 채택 "성별과 운동 선호도는 독립적이지 않다" (연관성이 있다)

   좋아함  좋아하지 않음
0   80       30
1   90       10
Chi2ContingencyResult(statistic=np.float64(9.045792112299468), pvalue=np.float64(0.0026330012530379632), dof=1, expected_freq=array([[89.04761905, 20.95238095],
       [80.95238095, 19.04761905]]))

In [35]:
## 0. 로우 데이터
# 총 210개의 행에서 남자 110명 / 여자 100명
# 남자 중 좋아함 80명 / 좋아하지 않음 30명 / 여자 좋아함 90명 / 좋아하지 않음 10명

## 1. 라이브러리 + 데이터 생성(시험 때엔 데이터 제공)
import pandas as pd
data = {
    '성별' : ['남자']*110 + ['여자']*100, ## 각 데이터 컬럼 * 인수 의 합
    '운동' : ['좋아함']*80 + ['좋아하지 않음']*30 + ['좋아함']*90 + ['좋아하지 않음']*10
}
df = pd.DataFrame(data)
df ## 총 210 데이터 확인

## 2. 교차표로 전환 (pd.crosstab())
df = pd.crosstab(df['성별'], df['운동']) ## 교차표 행에 들어갈 데이터 프레임 넣음
df ## 생성된 교차표 확인 - 문제 조건과 일치하는지 확인

## 3. 독립성 검정 (scipy.stats.chi2_contingency())
from scipy import stats
print(stats.chi2_contingency(df))
## 결과 : statistic=np.float64(9.045792112299468), pvalue=np.float64(0.0026330012530379632), dof=1, expected_freq=array([[20.95238095, 89.04761905], [19.04761905, 80.95238095]])
# p-value(0.0026) < 0.05 이므로 대립 채택 "성별과 운동 좋아함 여부는 독립적이지 않다"

Chi2ContingencyResult(statistic=np.float64(9.045792112299468), pvalue=np.float64(0.0026330012530379632), dof=1, expected_freq=array([[20.95238095, 89.04761905],
       [19.04761905, 80.95238095]]))

In [ ]:
import pandas as pd
df = pd.DataFrame({'좋아함': [80, 90],
                   '좋아하지 않음': [30, 10]},
                  index=['남자', '여자'])
print(df)

    좋아함  좋아하지 않음
남자   80       30
여자   90       10

In [ ]:
df = pd.DataFrame([[80, 30], [90, 10]],
                  columns=['좋아함','좋아하지 않음'],
                  index=['남자', '여자'])
print(df)

    좋아함  좋아하지 않음
남자   80       30
여자   90       10

In [ ]:
# df = [[80, 30], [90, 10]]

In [ ]:
from scipy import stats
print(stats.chi2_contingency(df))

Chi2ContingencyResult(statistic=9.045792112299468, pvalue=0.0026330012530379632, dof=1, expected_freq=array([[89.04761905, 20.95238095],
       [80.95238095, 19.04761905]]))

## 2-2 로우 데이터

In [ ]:
import pandas as pd
data = {
    '성별': ['남자']*110 + ['여자']*100,
    '운동': ['좋아함']*80 + ['좋아하지 않음']*30 + ['좋아함']*90 + ['좋아하지 않음']*10
}
df = pd.DataFrame(data)
print(df.head(3))

   성별   운동
0  남자  좋아함
1  남자  좋아함
2  남자  좋아함

In [ ]:
df = pd.crosstab(df['성별'], df['운동'])
df

운동  좋아하지 않음  좋아함
성별
남자       30   80
여자       10   90

In [ ]:
from scipy.stats import chi2_contingency
print(chi2_contingency(df))

Chi2ContingencyResult(statistic=9.045792112299468, pvalue=0.0026330012530379632, dof=1, expected_freq=array([[20.95238095, 89.04761905],
       [19.04761905, 80.95238095]]))

# 3.동질성 검정

## 3-1 교차표 데이터

In [37]:
## 카이제곱 동질성 검정 : 두 개 이상의 집단에서 분산의 동질성을 가졌는지 검정
# 방금 독립성 검정과 같은 chi2_contingency() 함수 사용 - 해석만 다름
# 귀무 : 모든 그룹의 분포 또는 비율은 동일 / 대립 : 각 그룹의 분포 또는 비율은 동일하지 않다
# 독립성 : 두 범주형 변수 간 연관성 존재?  | 동질성 : 두 그룹이 동일한 범주 분포를 보유?

## 문제 조건 : 학과에 따라 학교 공식 동아리에 가입한 학생의 수와 가입하지 않은 학생의 수를 비교하는 동질성 검사 실시
# 귀무 : 두 학과의 동아리 가입 비율은 동일 / 대립 : 두 학과의 동아리 가입 비율은 동일하지 않음
# 1. 교차표 데이터     2. 로우 데이터   - 주어진 데이터 유형에 따라 방법 상이

## 0. 교차표 데이터
# 통계학과 : 가입 50명 / 미가입 50명
# 컴퓨터공학과 : 가입 30명 / 미가입 70명

# 1. 라이브러리 및 데이터 프레임 생성
import pandas as pd
from scipy import stats

df = pd.DataFrame([[50,50],[30,70]]) ## 리스트 형태로 생성 가능 - 이게 덜 헷갈림
print(stats.chi2_contingency(df))
# 결과 : statistic=np.float64(7.520833333333334), pvalue=np.float64(0.006098945931214352), dof=1, expected_freq=array([[40., 60.], [40., 60.]])
# p-value(0.0060) < 0.05 이므로 대립 채택 "두 학과의 동아리 가입 비율은 동일하지 않다"

Chi2ContingencyResult(statistic=np.float64(7.520833333333334), pvalue=np.float64(0.006098945931214352), dof=1, expected_freq=array([[40., 60.],
       [40., 60.]]))

In [47]:
## 0. 로우 데이터 - 여기서는 랜덤으로 로우 데이터를 생성하기 위해 sample() 함수 사용할 것임
## 1. 라이브러리 및 데이터
import pandas as pd
data = {
    '학과' : ['통계학과']*100 + ['컴퓨터공학과']*100, ## 두 값은 합(+) 해 주어야 함
    '동아리 가입여부' : ['가입']*50+['미가입']*50+['가입']*30+['미가입']*70
}
df = pd.DataFrame(data)
df
df.sample(5)  ## 무작위 데이터 5개 (실행 시 마다 변동되는 것을 확인)

## 2. 교차표 변환 (pd.crosstab() 함수 사용)
df = pd.crosstab(df['학과'],df['동아리 가입여부']) ## crosstab() 함수 인자는 데이터 프레임을 직접 입력

## 3. 동질성 검정
from scipy import stats
print(stats.chi2_contingency(df))
# 결과 : statistic=np.float64(7.520833333333334), pvalue=np.float64(0.006098945931214352), dof=1, expected_freq=array([[40., 60.], [40., 60.]])
# p-value(0.0006) < 0.05 이므로 대립 채택 "두 학과의 동아리 가입 비율은 동일하지 않다"

Chi2ContingencyResult(statistic=np.float64(7.520833333333334), pvalue=np.float64(0.006098945931214352), dof=1, expected_freq=array([[40., 60.],
       [40., 60.]]))

In [ ]:
import pandas as pd
from scipy import stats
df = pd.DataFrame([[50, 50], [30, 70]])
print(stats.chi2_contingency(df))

Chi2ContingencyResult(statistic=7.520833333333334, pvalue=0.006098945931214352, dof=1, expected_freq=array([[40., 60.],
       [40., 60.]]))

## 3-2 로우 데이터

In [ ]:
import pandas as pd
data = {
    '학과': ['통계학과']*100 + ['컴퓨터공학과']*100,
    '동아리가입여부': ['가입']*50 + ['미가입']*50 + ['가입']*30 + ['미가입']*70
}
df = pd.DataFrame(data)
df.sample(5)

         학과 동아리가입여부
94     통계학과     미가입
116  컴퓨터공학과      가입
154  컴퓨터공학과     미가입
60     통계학과     미가입
197  컴퓨터공학과     미가입

In [ ]:
df = pd.crosstab(df['학과'], df['동아리가입여부'])
df

동아리가입여부  가입  미가입
학과
컴퓨터공학과   30   70
통계학과     50   50

In [ ]:
from scipy import stats
print(stats.chi2_contingency(df))

Chi2ContingencyResult(statistic=7.520833333333334, pvalue=0.006098945931214352, dof=1, expected_freq=array([[40., 60.],
       [40., 60.]]))

In [49]:
#### 어제 뭐 했는지 복기
# 1. 단일 표본 검정 2. 대응 표본 검정 3. 독립..?
# 1 ex. 팝콘 사이즈 120g 인가? 기본: 양측 검정, alternative 값(greater/less)으로 단측 검정 수행
# 1. 단일 표본 검정이란? 주어진 조건을 만족하는지 검정하는 것
# 2 ex. 두 집단 ... 두고 하는 검정인데

##### 기억이 안 나 카이제곱 하니까
# 1. 함수 scipy.stats.ttest_1samp(df, 120)
# 2. 대응 표본 검정 : 하나의 집단에서 시간차를 두고 두 번 측정하여 검정하는 것
# 2 ex. 약물의 효과가 있는가? 교육 프로그램 효과와 성과?
# 2. 함수 scipy.stats.ttest_rel(before, after, alternative='less/greater') # before-after 값을 기준으로 생각하면 alternative 값 구하기 쉬움
# 3. 독립 표본 검정 : 서로 다른 두 집단 사이의 평균이 서로 다름을 검정하는 것 "평균"이 다름을 검정
# 3. 함수 scipy.stats.ttest_ind(class1, class2) ## 모분산이 다르다고 가정하면 equal_var=(True/False) 옵션 추가

## 정규성을 만족하는가? stats.shapiro()
## (독립) 등분산성 만족? stats.levene() - 레베네가 아니라 레빈

In [52]:
####### 오늘 한 거 (카이제곱 검정)
# 1. 카이제곱 적합성 검정 2. 카이제곱 동질성 검정 3. 카이제곱 독립성 검정 (2-3 순서 바뀜)
# 1. 적합성 검정 : 특정 그룹의 조사결과가 일반적 비율에 적합한 지
# 1. ex 아이스크림 맛 선호도(빈도수로 조건 통일)
# 1. 함수 scipy.stats.chi_ 아 뭐였지

# 2. 독립성 검정 : 두 집단의 측정 결과가 서로 독립적인지 연관성이 있는지
# 2. ex 성별과 운동 선호도 간의 독립성 검정
# 2. 함수 scipy.stats.chi2_contingency()
# 2. 교차표 데이터 - 로우 데이터 방법 차이 유의 : 교차표(데이터 프레임 정의:리스트 형식 권장) / 로우 데이터(데이터-데이터프레임-교차표 변환)

# 3. 동질성 검정 : 두 집단의 모분산? 분산이 동일한지 검정하는 것
# 3. ex 학과별 동아리 가입여부
# 3. 함수 는 독립성 검정과 동일 scipy.stats.chi2_contingency()
# 3. 얘도 교차표/로우 데이터 방법 차이 유의 (교차표 생성 함수 crosstab() 인자는 데이터 프레임 직접 - pd.crosstab(['학과'],['가입여부']))

### 적합성 검정 함수 scipy.stats.chisquare() [싸이-스퀘어r]
### 동질성 검정이란 두 개 이상의 집단에서 "분산"이 동일한 범주의 분포를 갖는지 확인하는 것 ex. 두 학과의 동아리 가입 비율이 동일하다/동일하지 않다