<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/ch4_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part3/ch4/ch4_linear_regression.ipynb)

# 1. 상관관계

In [17]:
## 어떻게 빅분기 실기 합격률이 50%
# 상관 계수 : 두 변수 간 선형 정도 (+-1에 가까울수록 강함 / 0 가까우면 약함)
# 함수 pandas.DataFrame.corr() [콜rr]

## 문제 조건 : 학들의 키와 몸무게 데이터르 보고 상관 계수 구하기
# 1. 라이브러리 불러오기
import pandas as pd ## 판다스 사용

## 데이터 생성
data = {
    '키' : [150, 160, 170, 175, 165],
    '몸무게' : [42,50,70,64,56]
}
# 데이터 프레임 생성
df = pd.DataFrame(data)
df

## 2. 상관계수 계산
correlaton = df.corr() ## df에서 직접 .corr() 함수 사용
print(correlaton)
# 결 . 키    1.000000  0.919509
# 과 . 몸무게  0.919509  1.000000
## 키와 몸무게의 상관계수 = 0.919509

## 다른 방법
print(df['키'].corr(df['몸무게'])) ## 필요한 데이터 프레임만 가지고 corr() 함수 사용 - 키, 몸무게 순서 바껴도 동일

## 다른 상관계수 계산 시 method='spearman/kendall' 사용 (스피어만/켄달) *기본:피어슨
# Ex)
print(df.corr(method='spearman'))

            키       몸무게
키    1.000000  0.919509
몸무게  0.919509  1.000000
0.9195090879163765
       키  몸무게
키    1.0  0.9
몸무게  0.9  1.0

In [15]:
### 두 변수의 상관 계수와 t-검정 (t-검정 결과 -> 피어슨 상관 계수 값이 일반적)
## t-검정엔 역시 scipy.stats
from scipy import stats

## 상관 계수별 p-value 계산
# 1. 피어슨 상관 계수(기본)와 p-value
print(stats.pearsonr(df['몸무게'], df['키']))  ## 함수 stats.pearsonr() [피어슨-r] *r 붙이기
# 결과 : (statistic=np.float64(0.9195090879163766), pvalue=np.float64(0.02707945689558947))

# 2. 스피어만 상관계수
print(stats.spearmanr(df['몸무게'], df['키'])) ## stats.spearmanr() 함수 사용 얘도 스피어만 r 붙이기
# 결과 : (statistic=np.float64(0.8999999999999998), pvalue=np.float64(0.03738607346849874))

# 3. 켄달의 타우 상관 계수와 p-value
print(stats.kendalltau(df['몸무게'], df['키'])) ## 얘는 왜 함수에 이름도 들어감 kendalltau() [켄달-타우]
# 결과 : statistic=np.float64(0.7999999999999999), pvalue=np.float64(0.08333333333333333)

## 상관계수와 p-value -> 기본 : 스피어만 / 라이브러리는 scipy.stats.spearmanr() # 데이터 프레임 두 개 직접 넣어줌

PearsonRResult(statistic=np.float64(0.9195090879163766), pvalue=np.float64(0.02707945689558947))
SignificanceResult(statistic=np.float64(0.8999999999999998), pvalue=np.float64(0.03738607346849874))
SignificanceResult(statistic=np.float64(0.7999999999999999), pvalue=np.float64(0.08333333333333333))

In [ ]:
import pandas as pd

# 주어진 데이터
data = {
    '키': [150, 160, 170, 175, 165],
    '몸무게': [42, 50, 70, 64, 56]
}
df = pd.DataFrame(data)

# 상관계수 계산
correlation = df.corr()

print(correlation)

            키       몸무게
키    1.000000  0.919509
몸무게  0.919509  1.000000

In [ ]:
print(correlation.iloc[0,1])

0.9195090879163764

In [ ]:
print(df['키'].corr(df['몸무게']))
print(df['몸무게'].corr(df['키']))

0.9195090879163765
0.9195090879163765

In [ ]:
# 피어슨 상관계수 (기본값)
print(df.corr())

# 스피어맨 상관계수
print(df.corr(method='spearman'))

# 켄달타우 상관계수
print(df.corr(method='kendall'))

            키       몸무게
키    1.000000  0.919509
몸무게  0.919509  1.000000
       키  몸무게
키    1.0  0.9
몸무게  0.9  1.0
       키  몸무게
키    1.0  0.8
몸무게  0.8  1.0

In [ ]:
from scipy import stats
# 피어슨 상관계수와 p-value 계산
print(stats.pearsonr(df['몸무게'], df['키']))

# 스피어맨 상관계수와 p-value 계산
print(stats.spearmanr(df['몸무게'], df['키']))

# 켄달타우 상관계수와 p-value 계산
print(stats.kendalltau(df['몸무게'], df['키']))

PearsonRResult(statistic=0.9195090879163765, pvalue=0.02707945689558947)
SignificanceResult(statistic=0.8999999999999998, pvalue=0.03738607346849874)
SignificanceResult(statistic=0.7999999999999999, pvalue=0.08333333333333333)

# 단순 선형 회귀 분석

In [25]:
### 선형 회귀 분석 : 두 가지 이상의 변수 간 관계를 파악하기 위한 분석 방법
### 단순 선형 회귀 : 하나의 독립 변수~하나의 종속 변수와의 관계 (독립 변수가 두 개 이상: 다중 회귀 분석 -> 얘도 할 거임)
##  * 잔차 : 예측값과 실제 값의 차이

# 문제 조건 : 20명의 키와 몸무게에 관한 데이터를 바탕으로 회귀 모델 구축, 각 문제의 값 구하기
# (데이터 : 키-종속변수, 몸무게-독립변수)  ** 독립이 원인 / 종속이 결과임 - 생명과학 때 한 거 같은디

# 1. 라이브러리 불러오기 & 데이터 생성
import pandas as pd

data = {
    '키' : [150,160,170,175,165,155,172,168,174,158,162,173,156,159,167,163,171,169,176,161],
    '몸무게' :  [42, 50, 70, 64, 56, 48, 68, 60, 65, 52,
            54, 67, 49, 51, 58, 55, 69, 61, 66, 53] ## 몸무게는ㅜ 복붙
}
df = pd.DataFrame(data)
df # 데이터 프레임 확인

## 문제 1. 주어진 데이터로 최소제곱법을 이용한 단순 선형 회귀 모델을 구축하고 통계적 요약을 출력하시오
## 최소제곱법? ols() 함수임 근데 어떻게 씀
# 외워야 되네 statsmodels.formula.api 에서 ols() 사용

from statsmodels.formula.api import ols ## import 함수에 () 붙이는거 아님.

model = ols('키~몸무게', data=df).fit() ## 요게 단순 선형 회귀 모델 구축
print(model.summary())  ## 요게 통계적 요약 출력 : summary()
## 통계표 보고 결과 해석 가능해야 함
# 결정 계수 : R-squared 0.892 / 몸무게 p-value : 0.000 (0에 가까운 값이라는 뜻)
# 기울기 값 : coef (Intercept:절편 / 몸무게) 각각 확인

                            OLS Regression Results
==============================================================================
Dep. Variable:                      키   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                     148.0
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           4.04e-10
Time:                        15:04:13   Log-Likelihood:                -45.761
No. Observations:                  20   AIC:                             95.52
Df Residuals:                      18   BIC:                             97.51
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    115.0676      4.158     27.671      0.000     106.331     123.804
몸무게            0.8658      0.071     12.167      0.000       0.716       1.015
==============================================================================
Omnibus:                        0.985   Durbin-Watson:                   2.609
Prob(Omnibus):                  0.611   Jarque-Bera (JB):                0.336
Skew:                          -0.315   Prob(JB):                        0.845
Kurtosis:                       3.082   Cond. No.                         432.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [38]:
## 문제 2. 회귀 모델의 결정 계수를 구하시오 (별도 출력)
print("결정 계수 : ", model.rsquared)  ## statsmodels.formula.api ols() 는 아까 정의 여기서 결정계수는 rsquared 사용 (괄호 없음!)
# 결과 : 0.8915914350087264

## 문제 3. 회귀 모델에서 회귀 계수(기울기와 절편)를 구하시오
print("기울기 : ", model.params['몸무게']) ## model.params의 인덱스 지정을 통해 출력할 수 있음
print("절편 : ",model.params['Intercept']) ## 오. 놀랍게도 기울기가 '몸무게' 절편이 'Intercept'임
# 결과 : 기울기 :  0.8658438852380201 / 절편 :  115.06763904471865

## 문제 4. 회귀 모델에서 몸무게의 회귀 계수가 통계적으로 유의한지 검정했을 때의 p-value를 구하시오
# 두 가지 방법 존재 (1. print(format('값', ".10f"))   2. print("{:.10f}".format(model.pvalues['']))
print("p-value : ", model.pvalues['몸무게'])   ## 결과가 지수 값(e-10)으로 출력되므로 실수 형식으로 변경
print("p-value : ", "{:.10f}".format(model.pvalues['몸무게']))  ## 소수점 아래 10자리까지 실수 형태로 '몸무게'의 p-value 값을 출력
# 결과 : p-value :  0.0000000004   (지수값 : p-value :  4.0379325599303615e-10)
# model.pvalues['값'] 형식으로 출력할 수 있다는 것!

## 문제 5. 회귀 모델을 사용해 몸무게가 67일 때의 예측 키를 구하시오
# 예측을 수행하는 문제이므로 predict() 함수 사용
# 데이터 프레임을 새로 생성한 후에 예측 수행
new_data = pd.DataFrame({ '몸무게' : [67] }) ## 여기서 데이터 67의 값은 []로 묶어줌
result = model.predict(new_data) ## 예측 함수 인자값으로 데이터프레임
print("몸무게 67일 때 예측 키 :", result[0])  ## 인덱스 안 붙이면  0    173.079179 이렇게 출력되므로 [0]으로 값만 불러오기

## ** 결정계수 model.rsquare / 기울기 및 절편 model.params['데이터'] / p-value model.pvalues['데이터'] / 예측값 predict(data)    ** 형식에 유의

결정 계수 :  0.8915914350087264
기울기 :  0.8658438852380201
절편 :  115.06763904471865
p-value :  4.0379325599303615e-10
p-value :  0.0000000004
몸무게 67일 때 예측 키 : 173.07917935566599

In [47]:
## 문제 6. 회귀 모델의 잔차 제곱합을 구하시오
# 잔차 제곱합 = (잔차 제곱) 값 들의 합
# 잔차 : 실제 값 - 예측값    * 위에서 예측값 구하는 법을 학습했음

df['잔차'] = df['키'] - model.predict(df['몸무게'])  ## 종속 변수 - predict(독립변수) 라고 이해
print("잔차 제곱 합 : ", sum(df['잔차']**2)) ## 잔차 제곱 : df['잔차']**2 / 합은 sum() 함수로 묶어서 계산
# 결과 : 잔차 제곱 합 :  113.7422663888443

## predict(df)만 입력해도 알아서 독립변수 '몸무게'를 판단하여 실행함
df['잔차'] = df['키'] - model.predict(df)
print("잔차 제곱 합 : ", sum(df['잔차']**2)) #  결과 동일

## 문제 7. 회귀 모델의 MSE를 구하시오
# MSE : 평균 제곱 오차 = 잔차들의 평균 = mean(df['잔차']) 이건가

df['잔차'] = df['키'] - model.predict(df) # 잔차 구하기는 아까와 동일
MSE = (df['잔차']**2).mean() ## 잔차 제곱해서 평균 내장함수 .mean() 을 "뒤에" 붙여줌
print("평균 제곱 오차 : ", MSE)
## 결과 : 평균 제곱 오차 :  5.687113319442214
# 평균 *제곱* 오차니까 잔차 제곱에서 평균내는 것으로 이해

# *  신뢰구간 / 예측 구간 이것도 해야 하나 - 일단 보류

잔차 제곱 합 :  113.7422663888443
잔차 제곱 합 :  113.7422663888443
평균 제곱 오차 :  5.687113319442214

In [ ]:
import pandas as pd

data = {
    '키': [150, 160, 170, 175, 165, 155, 172, 168, 174, 158,
          162, 173, 156, 159, 167, 163, 171, 169, 176, 161],
    '몸무게': [42, 50, 70, 64, 56, 48, 68, 60, 65, 52,
            54, 67, 49, 51, 58, 55, 69, 61, 66, 53]
}
df = pd.DataFrame(data)

In [ ]:
from statsmodels.formula.api import ols
model = ols('키 ~ 몸무게', data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      키   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                     148.0
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           4.04e-10
Time:                        03:15:36   Log-Likelihood:                -45.761
No. Observations:                  20   AIC:                             95.52
Df Residuals:                      18   BIC:                             97.51
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    115.0676      4.158     27.671      0.000     106.331     123.804
몸무게            0.8658      0.071     12.167      0.000       0.716       1.015
==============================================================================
Omnibus:                        0.985   Durbin-Watson:                   2.609
Prob(Omnibus):                  0.611   Jarque-Bera (JB):                0.336
Skew:                          -0.315   Prob(JB):                        0.845
Kurtosis:                       3.082   Cond. No.                         432.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
print("결정계수:", model.rsquared)

결정계수: 0.8915914350087264

In [ ]:
print("기울기:", model.params['몸무게'])
print("절편:", model.params['Intercept'])

기울기: 0.8658438852380201
절편: 115.06763904471865

In [ ]:
print("pvalue:", model.pvalues['몸무게'])
print("pvalue:", "{:.10f}".format(model.pvalues['몸무게']))

pvalue: 4.0379325599303615e-10
pvalue: 0.0000000004

In [ ]:
new_data= pd.DataFrame({'몸무게':[67]})
result = model.predict(new_data)
print("몸무게가 67일 때의 예측 키:", result[0])

몸무게가 67일 때의 예측 키: 173.07917935566599

In [ ]:
df['잔차'] = df['키'] - model.predict(df)
print("잔차 제곱합:", sum(df['잔차']**2))

잔차 제곱합: 113.74226638884431

In [ ]:
df['잔차'] = df['키'] - model.predict(df)
MSE = (df['잔차'] ** 2).mean()
print('MSE:', MSE)

MSE: 5.687113319442214

In [ ]:
from sklearn.metrics import mean_squared_error
pred = model.predict(df['몸무게'])
mse = mean_squared_error(df['키'], pred)
print('MSE:', mse)

MSE: 5.687113319442214

In [ ]:
print("신뢰구간:\n", model.conf_int(alpha=0.05).loc['몸무게'])

신뢰구간:
 0    0.716337
1    1.015351
Name: 몸무게, dtype: float64

In [ ]:
new_data = pd.DataFrame({"몸무게": [50]})
pred = model.get_prediction(new_data)
result = pred.summary_frame(alpha=0.05)
print("예측값의 신뢰구간과 예측구간:\n", result)

예측값의 신뢰구간과 예측구간:
          mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0  158.359833  0.794986      156.68963     160.030037    152.820798

   obs_ci_upper
0    163.898869

# 다중 선형 회귀 분석

In [72]:
## 다중 선형 회귀 분석 : 두 개 이상의 독립 변수와 하나의 종속 변수 간의 관계를 분석

## 문제 조건 : 매출액, 광고비, 직원 수 데이터를 보고 다중선형 회귀 모델 구축 후 문제 답 구하기
# 광고비, 직원 수 : 독립 변수  / 매출액 : 종속 변수

## 문제에서 제시한 데이터로 데이터 프레임 생성
import pandas as pd

data = {
    '매출액' : [300, 320, 250, 360, 315, 328, 310, 335, 326, 280,
            290, 300, 315, 328, 310, 335, 300, 400, 500, 600],
    '광고비' : [70, 75, 30, 80, 72, 77, 70, 82, 70, 80,
            68, 90, 72, 77, 70, 82, 40, 20, 75, 80],
    '직원수' : [15, 16, 14, 20, 19, 17, 16, 19, 15, 20,
            14, 5, 16, 17, 16, 14, 30, 40, 10, 50] ## 데이터 값들은 복붙
}
df = pd.DataFrame(data)
df ## 데이터 프레임 생성 확인

## 문제 1. 데이터로 최소제곱법을 이용한 다중 선형 회귀 모델을 구축하고 통계적 요약 출력
from statsmodels.formula.api import ols
model = ols('매출액~광고비+직원수', data=df).fit() ### ols() 함수 인자 형식 좀 외워라. 하나도 못씀
## ols() 함수는 맨 땅에 그냥 씀. ols('종속~독립+독립+독립', data=데이터프레임).fit()
print(model.summary()) ## 통계적 "요약" 용어 자체가 힌트

                            OLS Regression Results
==============================================================================
Dep. Variable:                    매출액   R-squared:                       0.512
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     8.907
Date:                Tue, 16 Jun 2026   Prob (F-statistic):            0.00226
Time:                        17:06:58   Log-Likelihood:                -108.22
No. Observations:                  20   AIC:                             222.4
Df Residuals:                      17   BIC:                             225.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    101.0239     71.716      1.409      0.177     -50.284     252.331
광고비            1.8194      0.807      2.255      0.038       0.117       3.522
직원수            5.9288      1.430      4.147      0.001       2.912       8.945
==============================================================================
Omnibus:                       30.534   Durbin-Watson:                   1.354
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               64.655
Skew:                           2.444   Prob(JB):                     9.13e-15
Kurtosis:                      10.327   Cond. No.                         401.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [82]:
## ** 실전이다
## 문제 2. 광고비와 매출액의 상관계수 - 워. 실전 하자마자 모르겠ㄴ
print("상관 계수 : ", df['광고비'].corr(df['매출액']))  ## A와 B의 상관계수 = df['A'].corr(df['B']) ** 데이터 프레임.corr(데이터 프레임) ** 기억 좀
# 결과 : 상관 계수 :  0.13316981737040343

## 문제 3. 광고비와 매출액의 t-검정의 p-value - 했잖슴. scipy stats pvalues 맞나
from scipy import stats
print("p-value : ",stats.pearsonr(df['광고비'],df['매출액'])) ## pvalues 아니고 stats.pearsonr() 인자값으로 문제에서 언급한 모든 데이터 프레임 넣어줌
# 결과 : p-value :  PearsonRResult(statistic=np.float64(0.1331698173704034), pvalue=np.float64(0.5756778801904271)) = 0.5756...

## 문제 4. 회귀 모델의 결정 계수 - 이거 아까 한거잖슴 rsquare
print("결정 계수 : ", model.rsquared)  ## ...rsquare가 아니라 rsquared. d 가 붙는다고.
# 결과 : 결정 계수 :  0.5116964327009041

## 문제 5 : 회귀 모델에서 회귀 계수(기울기와 절편)를 구하시오
# print("기울기 : ", model.params(df['광고비'], df['직원수'])) ## 기울기는 독립 변수
# print("절편 : ", model.params(df['Intercept']))  ## 다 틀리네
print("회귀 계수 : ", round(model.params)) ## 인자값 없이 model.params 하면  모든 회귀 계수 확인 가능
# 결과 : 회귀 계수 :  Intercept    101.0    광고비            2.0    직원수            6.0  - 아까 summmary() 에서도 확인 가능

## 문제 6. 회귀 모델에서 광고비의 회귀 계수가 통계적으로 유의한지 검정했을 때의 p-value
print("p-value : ", model.pvalues['광고비'])  ## 문제에서 '광고비' 언급했으니 얘 인덱스 넣어줌 - 괄호 () 아님
# 결과 : p-value :  0.03764350647695994

## 문제 7. 광고비 50, 직원수 20인 데이터 있을 때, 회귀 모델에서의 예상 매출액
# 데이터 프레임 생성
new_data = pd.DataFrame({
    '광고비' : [50],
    '직원수' : [20]
}) ## 바로 데이터 프레임 직접 생성하기1!!!!!!
result = model.predict(new_data) # 얘는 잘 넘어감
print(result[0])  ## 결과 : 310.57033031815365

## 문제 8. 회귀 모델의 잔차의 제곱합을 구하시오 (잔차 = 실제(종속) - 예측(독립))
df['잔차'] = df['매출액'] - model.predict(df) ## 다중이니까 그냥 df로 알아서 실행하게끔
print("잔차 제곱 합 : ", sum(df['잔차']**2))
# 결과 : 잔차 제곱 합 :  58686.17827156107
# 왜 sum()은 값을 인자로 넣는데 평균은 뒤에 붙임 .?

## 문제 9. 회귀 모델의 MSE를 구하시오 (MSE : 평균 제곱 오차) -> 잔차 먼저 구하고 "제곱"오차니까 제곱한 거 평균내기
df['잔차'] = df['매출액'] - model.predict(df)
MSE = (df['잔차']**2).mean()
print("MSE : ", MSE) # 결과 : MSE :  2934.3089135780533  야르 굿-👌

상관 계수 :  0.13316981737040343
p-value :  PearsonRResult(statistic=np.float64(0.1331698173704034), pvalue=np.float64(0.5756778801904271))
결정 계수 :  0.5116964327009041
회귀 계수 :  Intercept    101.0
광고비            2.0
직원수            6.0
dtype: float64
p-value :  0.03764350647695994
310.57033031815365
잔차 제곱 합 :  58686.17827156107
MSE :  2934.3089135780533

In [93]:
## 문제 10. 각 변수별 95%의 신뢰 구간을 구하시오
# 아까 그냥 넘어간 문젠데 이게 나오네
print("95% 신뢰구간 :\n", model.conf_int(alpha=0.05)) ## model.conf_int(alpha=비율) 형태로 함수 사용 * 아까 summary() 통계에서도 확인 가능!

## 문제 11. 광고비 45, 직원수 22일 때, 95% 신뢰 구간과 예측 구간
# 얘도 그냥 넘어갔더니만.
new_data = pd.DataFrame({ ## 우선 문제에서 새로운 데이터를 제공했으니까 새 데이터 프레임 생성부터
    '광고비' : [45],
    '직원수' : [22]
})
pred = model.get_prediction(new_data) ## model.get_prediction() 함수 사용 : 예측 수행
result = pred.summary_frame(alpha=0.05) ## pred.summary_frame() 함수 사용 : 예측값, 신뢰 구간, 예측 구간 결과 | 95% 구간이므로 alpha=0.05 (5%를 의미)
print("예측값의 신뢰 및 예측 구간\n", result)

# 결과 해석 : mean_ci_lower  mean_ci_upper 값을 확인한다 - 95% 신뢰 구간 (265.855514 , 360.8059)
#  obs_ci_lower  obs_ci_upper  값 확인 - 예측 구간 (180.58875 , 446.072663)

## 신뢰 구간 문제 복기 - 번거롭네.
# 1. 각 변수별 95% 신뢰 구간 : 함수 conf_int(alpha=0.05) # 신뢰구간 % 나오면 -> 함수 인자값 alpha='값' 들어감 (라이브러리는 따로 X)
# 2. 새 데이터 + 95% 신뢰 구간 + 예측 구간 : 새 데이터 프레임 / model.get_predict(데이터프레임) : 예측 / pred.summary_frame(alpha=0.05) ## 역시 신뢰구간 문제(%)이므로 alpha=값

95% 신뢰구간 :
                    0           1
Intercept -50.283684  252.331429
광고비         0.116785    3.522069
직원수         2.912406    8.945105
예측값의 신뢰 및 예측 구간
          mean    mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0  313.330707  22.502058     265.855514       360.8059     180.58875

   obs_ci_upper
0    446.072663

In [ ]:
import pandas as pd
data = {
    '매출액': [300, 320, 250, 360, 315, 328, 310, 335, 326, 280,
            290, 300, 315, 328, 310, 335, 300, 400, 500, 600],
    '광고비': [70, 75, 30, 80, 72, 77, 70, 82, 70, 80,
            68, 90, 72, 77, 70, 82, 40, 20, 75, 80],
    '직원수': [15, 16, 14, 20, 19, 17, 16, 19, 15, 20,
            14, 5, 16, 17, 16, 14, 30, 40, 10, 50]
    }
df = pd.DataFrame(data)
print(df.head(3))

   매출액  광고비  직원수
0  300   70   15
1  320   75   16
2  250   30   14

In [ ]:
from statsmodels.formula.api import ols
model = ols('매출액 ~ 광고비 + 직원수', data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    매출액   R-squared:                       0.512
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     8.907
Date:                Mon, 17 Mar 2025   Prob (F-statistic):            0.00226
Time:                        03:15:38   Log-Likelihood:                -108.22
No. Observations:                  20   AIC:                             222.4
Df Residuals:                      17   BIC:                             225.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    101.0239     71.716      1.409      0.177     -50.284     252.331
광고비            1.8194      0.807      2.255      0.038       0.117       3.522
직원수            5.9288      1.430      4.147      0.001       2.912       8.945
==============================================================================
Omnibus:                       30.534   Durbin-Watson:                   1.354
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               64.655
Skew:                           2.444   Prob(JB):                     9.13e-15
Kurtosis:                      10.327   Cond. No.                         401.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
print("상관계수:", df['광고비'].corr(df['매출액']))

상관계수: 0.13316981737040343

In [ ]:
from scipy import stats
print(stats.pearsonr(df['광고비'], df['매출액']))

PearsonRResult(statistic=0.1331698173704034, pvalue=0.5756778801904271)

In [ ]:
print("결정계수(R-squared):", model.rsquared)

결정계수(R-squared): 0.5116964327009041

In [ ]:
print("회귀계수:\n", round(model.params))

회귀계수:
 Intercept    101.0
광고비            2.0
직원수            6.0
dtype: float64

In [ ]:
print("pvalue:", model.pvalues['광고비'])

pvalue: 0.03764350647695994

In [ ]:
new_data = pd.DataFrame({"광고비": [50], "직원수": [20]})
result = model.predict(new_data)
print("새로운 데이터의 매출액:", result)

새로운 데이터의 매출액: 0    310.57033
dtype: float64

In [ ]:
df['잔차'] = df['매출액'] - model.predict(df)
print("잔차 제곱합:", sum(df['잔차']**2))

잔차 제곱합: 58686.178271561075

In [ ]:
print(sum(model.resid**2))

58686.178271561075

In [ ]:
MSE = (df['잔차'] ** 2).mean()
print('MSE:', MSE)

MSE: 2934.3089135780533

In [ ]:
print("95% 신뢰구간:\n", model.conf_int(alpha=0.05))

95% 신뢰구간:
                    0           1
Intercept -50.283684  252.331429
광고비         0.116785    3.522069
직원수         2.912406    8.945105

In [ ]:
new_data = pd.DataFrame({"광고비": [45], "직원수": [22]})
pred = model.get_prediction(new_data)
result = pred.summary_frame(alpha=0.05)
print("예측값의 신뢰구간과 예측구간:\n", result)

예측값의 신뢰구간과 예측구간:
          mean    mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0  313.330707  22.502058     265.855514       360.8059     180.58875

   obs_ci_upper
0    446.072663

### 범주형 변수

In [98]:
## 범주형 변수 : 수치(int/float)가 아닌 데이터 -> 원-핫 인코딩으로 수치화 (필수)
# 이 부분은 간단히 참고하고 넘어감
import pandas as pd
import statsmodels.api as sm

df = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part3/ch4/study.csv')
df.head() # 데이터 확인 -  수치/변수 복합형

from statsmodels.formula.api import ols
model = ols('score~study_hours+material_type', data=df).fit() ## 공부시간, 학습유형에 따른 점수
print(model.summary())

## 내가 아는 원-핫 인코딩 : get.dummies()

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     991.9
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           4.42e-72
Time:                        17:30:30   Log-Likelihood:                -238.89
No. Observations:                 100   AIC:                             485.8
Df Residuals:                      96   BIC:                             496.2
Df Model:                           3
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept              59.2111      0.799     74.147      0.000      57.626      60.796
material_type[T.도서]    -8.6696      0.678    -12.778      0.000     -10.016      -7.323
material_type[T.독학]   -17.6129      0.634    -27.790      0.000     -18.871     -16.355
study_hours             0.4839      0.011     43.810      0.000       0.462       0.506
==============================================================================
Omnibus:                        1.754   Durbin-Watson:                   2.173
Prob(Omnibus):                  0.416   Jarque-Bera (JB):                1.216
Skew:                           0.231   Prob(JB):                        0.544
Kurtosis:                       3.280   Cond. No.                         228.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
import pandas as pd
import statsmodels.api as sm
# df = pd.read_csv("study.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part3/ch4/study.csv")
df.head()

   study_hours material_type  score
0           71            강의     95
1           34            독학     63
2           91            도서     95
3           80            독학     80
4           40            강의     79

In [ ]:
# 회귀 모델 생성
from statsmodels.formula.api import ols
model = ols('score ~ study_hours + material_type', data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     991.9
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           4.42e-72
Time:                        03:15:43   Log-Likelihood:                -238.89
No. Observations:                 100   AIC:                             485.8
Df Residuals:                      96   BIC:                             496.2
Df Model:                           3
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept              59.2111      0.799     74.147      0.000      57.626      60.796
material_type[T.도서]    -8.6696      0.678    -12.778      0.000     -10.016      -7.323
material_type[T.독학]   -17.6129      0.634    -27.790      0.000     -18.871     -16.355
study_hours             0.4839      0.011     43.810      0.000       0.462       0.506
==============================================================================
Omnibus:                        1.754   Durbin-Watson:                   2.173
Prob(Omnibus):                  0.416   Jarque-Bera (JB):                1.216
Skew:                           0.231   Prob(JB):                        0.544
Kurtosis:                       3.280   Cond. No.                         228.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 참고 자료

In [ ]:
# 참고1 원핫인코딩
pd.get_dummies(df).head()

   study_hours  score  material_type_강의  material_type_도서  material_type_독학
0           71     95              True             False             False
1           34     63             False             False              True
2           91     95             False              True             False
3           80     80             False             False              True
4           40     79              True             False             False

In [100]:
# 참고2 원학인코딩 drop_first
df = pd.get_dummies(df, drop_first=True) ## 첫 번째 범주형 이었던 데이터 컬럼 날려버림 (drop_first=True)
df.head()

   study_hours  score  material_type_도서  material_type_독학
0           71     95             False             False
1           34     63             False              True
2           91     95              True             False
3           80     80             False              True
4           40     79             False             False