<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/p10_type1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bae-v3/blob/main/part4/ch10/p10_type1.ipynb)

## 작업형1

In [6]:
##### 빅분기 두 번 보는건 좀 아니잖아. 원트 간다 D - 0.5
#### 문제 조건 : 제공된 데이터(subject_performance.csv)는 학생들이 각 문제를 풀었을 때의 정답 여부를 기록한 자료이다.
#### 각 문제는 대주제와 소주제로 분류되어 있다. 아래 수행 순서에 따라 데이터를 처리한 뒤, 구한 값을 [제출 형식]에 맞게 입력.
#### [수행 순서] 1. 소주제별 정답률 기록 : 정답률 = (해당 소주제의 정답 개수) / (해당 소주제의 전체 문제 풀이 수)
#### 2. 소주제들의 정답률 중 3 번째로 높은 값을 구하시오 (단, 정답률이 같은 경우 하나로 취급(중복 데이터는 취급 안 함))
#### [제출 형식] 반올림하여 소수 셋째 자리까지 작성

# 1. 라이브러리 및 데이터
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/subject_performance.csv")
print(df.head(4)) # 데이터 확인

# 수행순서 1. 소주제별 정답률
cond = df['is_correct'] == True ## 정답개수 (소주제 : ['sub_topic'])
# df['correct'] = df.loc(cond, 'sub_topic').sum() / 전체 문제 풀이 수가 뭐지.

# 모범 답안 - 소주제별 정답률
acc = df.groupby('sub_topic')['is_correct'].mean() ## 소주제"별" 정답률 이니까 groupby() 써야지 / 정답률을 .mean()으로 평균값을 쓰네
# 상위 4개 추출 후 중복 제거 (풀이 1)
result = acc.nlargest(4).drop_duplicates() ## .nlargest(정수) 상위 '정수' 개의 값 출력 / .drop_cuplicates() 중복 값 제거 : 중복값은 취급 안 할 때
print(round(result, 3)) # 3 번째로 높은 값 확인 : Calculus      0.674
# 답안 : 0.674

# 소주제별 정답률 (풀이 2) - 정렬 후 중복 제거
result = acc.sort_values(ascending=False).drop_duplicates() ## 역시 중복제거(.drop_duplicates()) / sort_values(ascending=False) : 내림차순으로 정렬
print(round(result, 3)) # 전체 순위 확인 가능 : 3 번째 값 확인

### 파이썬 함수 암기 & 조합 싸움이네 완전

        major_topic             sub_topic  student_id  is_correct
0       Mathematics  Discrete Mathematics         359           1
1       Mathematics  Discrete Mathematics         621           1
2  Computer Science             Databases        1366           1
3       Mathematics  Discrete Mathematics        1377           0
sub_topic
Algorithms    0.787
Mechanics     0.694
Calculus      0.674
Name: is_correct, dtype: float64
sub_topic
Algorithms              0.787
Mechanics               0.694
Calculus                0.674
Quantum                 0.668
Electromagnetism        0.659
Discrete Mathematics    0.644
Databases               0.641
Name: is_correct, dtype: float64

In [15]:
#### 문제 조건 : 제공된 데이터(cafe.sales.csv)는 2024년 4월부터 2025년 12월까지의 카페 메뉴 판매 이력이다.
#### 소문항을 각각 구한 다음 [제출 형식] 맞춰 답안 페이지에 입력
#### 제공 데이터 : 데이터 샘플 확인

# 1. 라이브러리 및 데이터
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/cafe_sales.csv")
print(df.head(4)) # 데이터 확인

## 문제 1. 연~월별 총 매출액을 계산하여 큰 순서대로 정렬했을 때, 2번째로 큰 매출액을 입력하시오
# 2. 연~월별 : 날짜 데이터 함수 있었는데 / 매출액 ['price'] / 큰 순서대로 정렬(내림차) sort_values(ascending=False)
# 연~월 변환
df['order_date'] = pd.to_datetime(df['order_date']) ## pd.to_datetime('데이터 프레임')
df['year_month'] = df['order_date'].dt.to_period("M") ## 월 까지를 기준으로 기간 변경
print(df.head()) ## 연-월 데이터 변환 및 생성 확인

# 연-월"별" 이므로 그룹화하여 총 매출액 계산
prices = df.groupby("year_month")['price'].sum() ## 'year_month'그룹화한 데이터의 'price(총 매출액)'의 .sum() 합계
# 상위 2 번째 값 : nlargest() 사용
print(prices.nlargest(2)) # 결과 중 두 번째 값 : 2025-07    328741
# 답안 : 328,741


## 문제 2. 연-월별 총 매출액이 4 번째로 큰 연-월을 찾으시오. 해당 연-월의 데이터에서 카테고리별 매출 합계 계산하고, 그중 최댓값 구하시오
# 아까 사용한 nlargest()
print(prices.nlargest(4)) # 이번엔 4 번째 결과값 : 2024-10    309026
# 4 번째로 큰 연-월 : 2024-10

# 2024-10 데이터에서 카테고리"별" 매출 합계 계산. 후 최댓값
# 이중 그룹화인가.?

## 답을 보고 이해부터 해보기로 했다.
# 연-월별 총 매출액 중 상위 4개 데이터 추출
top4 = prices.nlargest(4) # 아까 그 연-월 그룹화 데이터의 총 매출액 상위 4개 데이터 추출
indx = top4.index[3] # 4 번째로 큰 데이터는 인덱스 3 번에 저장되어 있음. 해당 데이터 추출

# 연-월 데이터 중 4 번째로 매출액 큰 데이터의 연-월과 동일한 데이터만 필터링
cond = df['year_month'] == indx  ## 값으로 보자면, 2024-10 데이터만.
df = df[cond] # 필터링 데이터로만 재정의

# 해당 연-월의 카테고리"별" 매출 합계. 중 최댓값
total = df.groupby('category')['price'].sum().max()
print(total) # 결과 : 104660
# 답안 : 104660

### .... 문제만 봐서 답을 유추하기가 쉽진 않겠는데. 풀다보면 감이 오나.

         order_date  category      item  price
0  2025.03.08 23:30       tea  GreenTea   6861
1  2025.10.01 13:05    coffee     Latte   6080
2  2025.04.30 17:32  smoothie     Mango   6116
3  2025.12.07 06:45       tea  BlackTea   7807
           order_date  category      item  price year_month
0 2025-03-08 23:30:00       tea  GreenTea   6861    2025-03
1 2025-10-01 13:05:00    coffee     Latte   6080    2025-10
2 2025-04-30 17:32:00  smoothie     Mango   6116    2025-04
3 2025-12-07 06:45:00       tea  BlackTea   7807    2025-12
4 2024-04-10 00:40:00   dessert    Cookie   7964    2024-04
year_month
2025-03    347848
2025-07    328741
Freq: M, Name: price, dtype: int64
year_month
2025-03    347848
2025-07    328741
2025-05    311810
2024-10    309026
Freq: M, Name: price, dtype: int64
104660

In [24]:
#### 문제 조건 : 제공된 데이터(hamspam.csv)는 문자 메시지 내용과 스팸 여부를 담고 있다. 아래 수행 순서에 따라
#### 데이터를 처리한 뒤, 구한 값을 [제출 형식]에 맞춰 답안 페이지에 입력하시오.
#### [수행 순서] 1. 각 메시지의 단어 개수를 띄어쓰기(공백) 기준으로 계산하시오
#### 2. 스팸 메시지의 평균 단어 개수와 정상 메시지의 평균 단어 개수를 각각 구하시오.
#### 3. 두 평균의 차이의 절댓값을 구하여 입력하시오
#### [제출 형식] 반올림하여 소수 셋째 자리까지 작성

# 아까는 날짜. 이번엔 글자. 처음엔 뭐였냐, 국가별 데이터? 각종 유형 다 알고 있어야 득점인건가. str.함수 쓰겠네.
# 1. 라이브러리 및 데이터
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")
print(df.head(5)) # 데이터 확인

## 문제 1. 각 메시지의 단어 개수를 띄어쓰기 기준으로 계산.
# 방법은 따로 있겠지만 (띄어쓰기 없애기 -> 데이터 길이 계산) 으로 간다
# df['text'] = df['text'].str.replace(" ", "")
# df['len'] = len(df['text'])
# print(df['len'])  ## 그렇게 실패를 하고 말았다는 것. 왜 2000으로 통일됨.

# 해답
df['단어'] = df['text'].str.split() ## 공백 기준으로 단어 분류하여 새 컬럼 생성 - 생각해보니 split() 공부했던 거였고.
print(df.head()) ## 단어 컬럼 확인
df['단어수'] = df['단어'].str.len() ## len() 함수는 .len()을 뒤에 붙여도 되고, len(값)으로 인자를 넣어줘도 된다. // 단어 개수 세기
print(df.head())  ## 단어수 컬럼 확인 * 문자, 문자열 작업 시 .str 항시 확인할 것!

## 문제 2. 스팸 메시지 평균 단어 개수 / 정상 메시지 평균 단어 개수
# 실패 후 답안 해석 : 각각 df.loc(cond, '단어수').mean() 으로 실패 ...

m = df.groupby('label')['단어수'].mean() ## label 그룹별 단어 개수의 평균 구하기
diff = abs(m['ham']-m['spam']) ## 두 그룹 값의 차이(뭐가 더 많은지 모르니까 절댓값 처리)
print(round(diff, 3)) # 소수 셋째 반올림
# 결과 및 답안 : 0.047

## 피곤해졌다. 오늘-내일 중 봐야할 거. 2 유형 concat() 하여 원-핫 인코딩 후 분리까지. 선형 회귀 LinearRegressor (?) 한 번 더 확인
## 불균형 데이터 처리(참고) / 행 제거 조건 drop OR dropna / 인코딩 사용 조건(원-핫, 레이블) / 카이제곱검정(적합도, 독립성, 동질성(?))
## 상관 및 회귀 계수 / .loc - .iloc / 사분위수 계산 + 각종 내장함수 (1유형용) / 잔차 , 로지 - 오즈비 한 번 씩 훑기 (점검) 잔차이탈도 llf * -2 였던가.
## 맞다 그거. 만족도 오류율 정밀도 한 두 번 복기.

  label                                               text
0   ham  Incididunt tempor elit sit do aliqua eiusmod a...
1   ham       Adipiscing tempor lorem ipsum dolore tempor.
2  spam    Tempor tempor magna sed incididunt consectetur.
3   ham  Consectetur incididunt amet adipiscing amet lo...
4   ham                  Sit ipsum labore sit do sit elit.
  label                                               text  \
0   ham  Incididunt tempor elit sit do aliqua eiusmod a...
1   ham       Adipiscing tempor lorem ipsum dolore tempor.
2  spam    Tempor tempor magna sed incididunt consectetur.
3   ham  Consectetur incididunt amet adipiscing amet lo...
4   ham                  Sit ipsum labore sit do sit elit.

                                                  단어
0  [Incididunt, tempor, elit, sit, do, aliqua, ei...
1  [Adipiscing, tempor, lorem, ipsum, dolore, tem...
2  [Tempor, tempor, magna, sed, incididunt, conse...
3  [Consectetur, incididunt, amet, adipiscing, am...
4          [Sit, ipsum, labore, sit, do, sit, elit.]
  label                                               text  \
0   ham  Incididunt tempor elit sit do aliqua eiusmod a...
1   ham       Adipiscing tempor lorem ipsum dolore tempor.
2  spam    Tempor tempor magna sed incididunt consectetur.
3   ham  Consectetur incididunt amet adipiscing amet lo...
4   ham                  Sit ipsum labore sit do sit elit.

                                                  단어  단어수
0  [Incididunt, tempor, elit, sit, do, aliqua, ei...   10
1  [Adipiscing, tempor, lorem, ipsum, dolore, tem...    6
2  [Tempor, tempor, magna, sed, incididunt, conse...    6
3  [Consectetur, incididunt, amet, adipiscing, am...   12
4          [Sit, ipsum, labore, sit, do, sit, elit.]    7
0.047

### 문제1

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/subject_performance.csv")

df.head()

        major_topic             sub_topic  student_id  is_correct
0       Mathematics  Discrete Mathematics         359           1
1       Mathematics  Discrete Mathematics         621           1
2  Computer Science             Databases        1366           1
3       Mathematics  Discrete Mathematics        1377           0
4           Physics             Mechanics         535           0

In [ ]:
# 풀이1

# 1. 소주제별 정답률 계산 (정답1, 오답0)
acc = df.groupby("sub_topic")["is_correct"].mean()

# 2. 내림차순 정렬 후 중복 제거
result = acc.sort_values(ascending=False).drop_duplicates()

print(round(result, 3))
#정답: 0.674

sub_topic
Algorithms              0.787
Mechanics               0.694
Calculus                0.674
Quantum                 0.668
Electromagnetism        0.659
Discrete Mathematics    0.644
Databases               0.641
Name: is_correct, dtype: float64

In [ ]:
# 풀이2
# 1. 소주제별 정답률 계산 (정답1, 오답0)
acc = df.groupby("sub_topic")["is_correct"].mean()

# 2. 상위 4개 추출 후 중복 제거
result = acc.nlargest(4).drop_duplicates()

print(round(result, 3))
#정답: 0.674

sub_topic
Algorithms    0.787
Mechanics     0.694
Calculus      0.674
Name: is_correct, dtype: float64

In [ ]:
# 3번째로 높은 정답률 출력
print(round(result.iloc[2],3))

0.674

### 문제2

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/cafe_sales.csv")
df.head()

         order_date  category      item  price
0  2025.03.08 23:30       tea  GreenTea   6861
1  2025.10.01 13:05    coffee     Latte   6080
2  2025.04.30 17:32  smoothie     Mango   6116
3  2025.12.07 06:45       tea  BlackTea   7807
4  2024.04.10 00:40   dessert    Cookie   7964

In [ ]:
# 2-1
# 1. order_date → 연-월 변환
df["order_date"] = pd.to_datetime(df["order_date"])
df["year_month"] = df["order_date"].dt.to_period("M")
df.head()

# 2. 연-월 단위로 그룹화하여 각 월의 총 매출액(price 합계)을 계산
monthly_sales = df.groupby("year_month")["price"].sum()

# 3. 연-월별 총매출액 중 상위 2개만 추출
print(monthly_sales.nlargest(3))

# 정답: 328741

year_month
2025-03    347848
2025-07    328741
2025-05    311810
Freq: M, Name: price, dtype: int64

In [ ]:
# 2-2

# 1. 연-월별 총매출액 중 상위 4개만 추출
top4 = monthly_sales.nlargest(4)
target_ym = top4.index[3]

# 2. 4번째로 큰 연-월에 해당하는 데이터만 추출
cond = df["year_month"] == target_ym
df = df[cond]

# 3. 해당 연-월의 카테고리별 매출 합계 중 최댓값 계산
cate = df.groupby("category")["price"].sum()

print(cate.max())

# 정답: 104660

104660

### 문제3

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")
df.head()

  label                                               text
0   ham  Incididunt tempor elit sit do aliqua eiusmod a...
1   ham       Adipiscing tempor lorem ipsum dolore tempor.
2  spam    Tempor tempor magna sed incididunt consectetur.
3   ham  Consectetur incididunt amet adipiscing amet lo...
4   ham                  Sit ipsum labore sit do sit elit.

In [ ]:
# 풀이1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")

# 1. 각 메시지의 단어 개수 구하기 (띄어쓰기 기준)
df["단어"] = df["text"].str.split()
df["단어수"] = df["단어"].str.len()
df.head()

# 체크 (2번째 행)
# print(df["text"][1])
# print(df["단어"][1])
# print(df["단어수"][1])

# 2. 스팸과 정상 메시지의 평균 단어 수 구하기
m = df.groupby("label")["단어수"].mean()

# 3. 두 평균 차이의 절댓값 구하기
diff = abs(m["spam"] - m["ham"])

# 4. 소수 셋째 자리까지 반올림
print(round(diff, 3))

# 정답: 0.047

0.047

In [ ]:
# 풀이2
import pandas as pd
# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")


# 1. 각 메시지의 단어 개수 구하기 (띄어쓰기 기준)
df["단어수"] = df["text"].str.count(" ") + 1
df.head()

# 2. 스팸과 정상 메시지의 평균 단어 수 구하기
cond1 = df["label"] == "spam"
cond2 = df["label"] == "ham"
m1 = df[cond1]["단어수"].mean()
m2 = df[cond2]["단어수"].mean()

# 3. 두 평균 차이의 절댓값 구하기
diff = abs(m1 - m2)

# 4. 소수 셋째 자리까지 반올림
print(round(diff, 3))

# 정답: 0.047

0.047